### PR TITLE
Made scroll wheel zoom work when fov > 0

### PR DESCRIPTION
**Pull request by inclement**
This copies the way right click zooming is handled.

### CODE REVIEW

**Comment by inclement** [comment]
It looks like the checks all failed for reasons unrelated to the PR.

**Comment by Eric89GXL** [comment]
What is the problem that you're having that this fixes?

**Comment by inclement** [comment]
@Eric89GXL If the fov of a PerspectiveCamera is zero, the scroll wheel zooms in and out (by modifying self._scale_factor). However, if the fov is non-zero, the scroll wheel does nothing.

Using right click and dragging zooms in and out regardless of the fov, because it modifies both self._scale_factor and self._distance, so I copied the latter modification.

**Comment by almarklein** [comment]
> if the fov is non-zero, the scroll wheel does nothing.

It works for me. Did you try latest master?

**Comment by almarklein** [comment]
Oh wait, what camera are you using exactly?

**Comment by almarklein** [comment]
Ah now I see. It's when a distance is specified. I overlooked that, sorry.

**Comment by almarklein** [comment]
Merging. Travis is half-down, so we don't want to wait for that. Locally checked that this worked. Thanks!

**Pull request merged**
