### PR TITLE
WIP: Travis if else fix

### PR DESCRIPTION
**Pull request by kmuehlbauer**

### CODE REVIEW

**Comment by djhoese** [comment]
So...what happened here? How long has this been broken?

**Comment by djhoese** [comment]
And why wasn't this valid before?

**Comment by kmuehlbauer** [comment]
Most likely through my latest changes.

**Comment by djhoese** [comment]
I'm curious if the lines at the end of some of your higher up conda/pip commands is screwing things up?

**Comment by djhoese** [comment]
Nevermind those were there before.

**Comment by kmuehlbauer** [comment]
Wouln't it be easier to move this stuff into a shell-script?

**Comment by djhoese** [comment]
Probably. Also I realized I was being dumb. The `pip` command I was looking at before had `-q` so it wasn't going to have any output anyway. I was also looking at a `minimal` environment and was confused why the `full` if statement had no output (it wasn't supposed to). So...I'll have to look at this again.

**Comment by kmuehlbauer** [comment]
Gnarf, according to the docs it is `[[ "$TRAVIS_OS_NAME" == "osx" ]]`.

**Comment by kmuehlbauer** [comment]
Closing as the problem source doesn't exist.

**Pull request closed without merging**
