### PR TITLE
Fix VolumeVisual modifying user provided data in-place

### LINKED ISSUE #1727: VolumeVisual.set_data method and copy=False may lead to unexpected behavior
An issue recently arose in the napari repo (see napari/napari#575) in which calling the `VolumeVisual.set_data()` method was altering the input data and causing unexpected results (but only with float32 input data).  We eventually realized it was caused by line 477 below in the `set_data()` method, in which the data is converted to float32 with `copy=False`.

https://github.com/vispy/vispy/blob/8b61cd439076aa3f50ac5f6dacb4c0af8c1d0684/vispy/visuals/volume.py#L477-L483

I realize we can simply copy the data on our end before calling the `VolumeVisual.set_data()` method, but I'm wondering whether the default behavior shouldn't be to copy the volume before applying the clim normalizations, so as to avoid unexpectedly overwriting the input data)?  (it was particularly hard to find due to the fact that the memory address of the input volume is unchanged _only_ for float32 data)

### PR DESCRIPTION
**Pull request by tlambert03**
This PR copies data by default in `VolumeVisual.set_data`, and adds a copy parameter to the method for those who want to maintain the existing behavior (wherein float32 data is not copied).
see #1727 for full discussion.

### CODE REVIEW

**Comment by djhoese** [comment]
Thanks for this. Looks like the CIs don't like your docstring.

**Comment by tlambert03** [comment]
whoops.  forgot to add the new parameter to the docstring... sorry.  let's see if that fixes it.

**Comment by djhoese** [comment]
Are there any existing tests where you can add a check for this?

**Comment by tlambert03** [comment]
I'll try to look through your tests later today to see where it might fit best.
Thanks!

**Comment by tlambert03** [comment]
OK added a test to confirm data integrity for a variety of dtypes, and also one that makes sure calling `set_data(..., copy=False)` actually _does_ change the data if it's `float32` (indicating that no copy operation was performed).  Hope that will help!

**Comment by tlambert03** [comment]
don't understand why the colorbar example test is failing... don't see any connections to the changes in this PR.  closing and reopening to trigger a rebuild...

**Pull request merged**
