### PR TITLE
Handle deprecation warnings for numpy 1.20

### PR DESCRIPTION
**Pull request by hmaarrfk**
```
  %PREFIX%\lib\site-packages\vispy\gloo\program.py:114: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    'bvec3':        (np.bool,    3),
```

### CODE REVIEW

**Comment by djhoese** [comment]
I just tackled a lot of these in #2004

**Comment by hmaarrfk** [comment]
ok.

**Comment by djhoese** [comment]
Thanks.

**Comment by hmaarrfk** [comment]
thank you!

**Pull request closed without merging**
