### PR TITLE
enable remove_comments in shader preprocessor

### PR DESCRIPTION
**Pull request by ombschervister**
To #1163 for allow comments on own language

### CODE REVIEW

**Comment by campagnola** [comment]
I think it is currently disable because it messes with the line numbers in error reports. Can you check whether this is true?
If so, perhaps we can just replace commented lines with blank lines.

**Comment by ombschervister** [comment]
Ok, I will do it

**Comment by ombschervister** [comment]
Yes, you are right about incorrect line number in error reports. And i tried to fix it in this pull request.

But there is incorrect line number because adding "#version 120" too.

**Comment by Eric89GXL** [comment]
@ombschervister is this ready to go from your end? Can you add a small test that would fail on `master` (e.g., with unicode in a GLSL comment) but passes now?

**Comment by Eric89GXL** [comment]
Also, you need to adjust one of the existing tests, since it fails now

**Pull request closed without merging**
