### PR TITLE
Update WebGL event loop

### PR DESCRIPTION
**Pull request by rossant**
Minor changes in the WebGL event loop required for benchmarking the IPython backend.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
Travis and AppVeyor errors seem unrelated -- some new problem with initializing GLFW on Travis and an illegal instruction problem on AppVeyor I've seen but haven't had time to track down. We might need to disable AppVeyor for a bit :(

**Comment by Eric89GXL** [comment]
+1 for merge, if nobody else chimes in over the next couple of days I'll merge

**Comment by almarklein** [comment]
I do not really understand these changes, but I suppose this is because some of it is in vispy.min.js?

**Comment by rossant** [comment]
Yes, see https://github.com/vispy/vispy.js/commit/f4da4c6d7f9069eed51bd117e359abbd87c03e3a

Basically we now have better control on what happens at every iteration in the WebGL game loop. This is useful for benchmarking.

**Comment by almarklein** [comment]
+1 then :)

**Comment by Eric89GXL** [comment]
CI failures are unrelated, so I'll go ahead and merge. We'll tackle the CI issues separately.

**Pull request merged**
