### PR TITLE
WIP: Test osmesa

### PR DESCRIPTION
**Pull request by kmuehlbauer**
This PR extends #1569. It just tests the osmesa handling, so `.travis-yml` is stripped down to only osmesa.

- [x] 1. Test  current approach (not successful, latest commit https://github.com/vispy/vispy/pull/1570/commits/0a28664a14ecc2cb94c655295f0208ecf8881713)
- [x] 2. Test conda-forge only approach (do not use Travis system libs, but depend on conda-forge) (not successful, latest commit https://github.com/vispy/vispy/pull/1570/commits/89c1b319832b692c3ff4440580013fe58911516f)
- [ ] 3. Test Travis only approach (do not use conda-forge)
- [ ] 4. Test osmesa recompilation using 2.
- [ ] 5. Test osmesa recompilation using 3.
- [ ] tbc ?

ToDo/Think about List:
- [x] get glfw into conda-forge, see https://github.com/conda-forge/staged-recipes/issues/4395
- [ ] add mesalib 8bit color channel builds to conda-forge, see https://github.com/conda-forge/mesalib-feedstock/issues/22
- [ ] compile conda-forge `libglu` `--with-osmesa`.
- [ ] tbc

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
While the conda-env is now conda-forge only, somehow there are now problems with the X11-stuff. At least this is indicated by the error messages. We could try to use CentOS like conda-forge is using to minimize library clashes. ATM I do not know how to proceed since there are so many options for tweaking here.

**Comment by kmuehlbauer** [comment]
@djhoese The `OSError: /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1: undefined symbol: _glapi_tls_Dispatch` error [you mentioned](https://github.com/vispy/vispy/pull/1569#issuecomment-459970236) was visible the first time in this PR #1353 comment [here](https://github.com/vispy/vispy/pull/1353#issuecomment-328016685). I had a hunch back then, that this might be due to the provided osmesa-lib. But we didn't resolve this, unfortunately.

**Comment by kmuehlbauer** [comment]
Compiling glfw won't work without system-libs or we need to get it into conda-forge.

**Comment by julienr** [comment]
@kmuehlbauer I'm not sure I understand fully the background of this issue, but it would help you if I could update my [vsipy_osmesa_docker](https://github.com/julienr/vispy_osmesa_docker) repo to use a newer version of osmesa ? If yes, I could give it a shot. Do you specifics glu/mesa/ubuntu versions in mind that you need ?

**Comment by kmuehlbauer** [comment]
@julienr Thanks for coming back to this. Atm we have problems tracking down the source of errors we see.

Would be good to have versions using trusty (our setup Travis), xenial and CentOS based (same as conda-forge is using). For osmesa I honestly do not know.

**Comment by kmuehlbauer** [comment]
closing in favour of #1569

**Pull request closed without merging**
