### PR TITLE
ENH: AxisVisual

### LINKED ISSUE #549: ENH: Axis visual
Should have the following features:
* Rectangular widget that can be stacked in a `Grid` next to a `ViewBox`; displays an axis line with ticks and text.
* Can also be placed inside `ViewBox`
* Responds nicely to non-linear coordinate systems, and ticks appear/disappear smoothly as the view is zoomed (similar to `GridLines`)
* Spacing / length / location of ticks can be specified manually, or automatically by 'linking' the `Axis` to another coordinate system (usually `viewbox.scene`).
* Should be designed with customization in mind, especially wrt. tick selection and text formatting.

### PR DESCRIPTION
**Pull request by Eric89GXL**
Follow-up on #829 

Closes #549.

Todo:

* [x] Bounds
* [x] Tweak examples
* [ ] Basic tests

### CODE REVIEW

**Comment by nippoo** [comment]
Hey @Eric89GXL - sorry I didn't get time to finish this. Hope some of my code is reusable! as @rossant said - I've got a bit too much going on in the day job at the moment, and since we're not using the SceneCanvas (for now, at least), the lower-level stuff is a higher priority for the moment. Thanks for taking it over!

**Comment by Eric89GXL** [comment]
Okay, ready for a review/merge from my end @campagnola 

This is by no means feature-complete -- it is pretty bare bones currently. There are *many* possible future enhancements, and I have made a list in the `vispy/visuals/axis.py` file. I think it would be good to merge this version, though, because 1) in this state it is usable by a careful user for many use cases, and critically 2) different people can work on making enhancements independently.

`examples/basics/visuals/lineplot_axes.py`:

screenshot from 2015-06-05 09 57 30

`examples/basics/scene/line_update.py`:

screenshot from 2015-06-05 09 57 40

**Comment by Eric89GXL** [comment]
@nippoo feel free to take a look at how I chopped up your code as well -- e.g. I made use of the transform system to figure out how the text should be aligned.

**Comment by campagnola** [comment]
Whee! We finally get our axes.

However, the axes aren't visible for me in `line_update.py`, and `lineplot_axes.py` segfaults. But other than that it's GREAT  ;)

**Comment by Eric89GXL** [comment]
Weird, I wonder why it segfaults for you. I'm not doing anything particularly tricky in the code. Can you try commenting out the line that creates the text visual, and the line that draws the text visual, and see if that gets rid of the segfault? I'm guessing that is at fault.

**Comment by campagnola** [comment]
The segfault appears to happen in the `axis.draw` calls. I'll do a little more digging this evening..

**Comment by Eric89GXL** [comment]
Yeah, probably in the subsection of that call that creates or draws the text would be my guess.

**Comment by Eric89GXL** [comment]
@bollu can you try this branch and the two examples mentioned above when you get a chance?

**Comment by campagnola** [comment]
I just tried this again and I can't reproduce the segv. Ok to merge?

**Comment by Eric89GXL** [comment]
Yeah we can merge this and iterate as necessary

**Comment by campagnola** [comment]
Hooray!
Thanks @Eric89GXL and @nippoo.

**Comment by Eric89GXL** [comment]
Thanks for the reviews, now we just need to integrate it with the plot
widget in a nice way, amongst many other enhancements :)

**Comment by campagnola** [comment]
Should be easy if we make an axis widget first; then just stack everything together in a grid and add some code to link the axis domain to the viewbox. I might work on this tomorrow unless you're itching to get it done sooner :)

**Comment by Eric89GXL** [comment]
No, please go for it if you have time.

**Pull request merged**
