### PR TITLE
Cleanup collections code

### LINKED ISSUE #797: Fix remaining small issues in new collections code
See comments in code #788

Overview:
* do we need empty `__init__.py` in glsl subdirectories?
* make module names pep8 compliant (no underscores)
* remove whitespace between parameter descriptions in docstrings.

cc @rossant @rougier

### PR DESCRIPTION
**Pull request by bollu**
Closes #797
also addresses issues from #788

cc @almarklein, @rougier, @Eric89GXL

### CODE REVIEW

**Comment by bollu** [comment]
I have not renamed modules like ```base_collection``` -> ```basecollection```. I'll do it if this is considered required.

**Comment by Eric89GXL** [comment]
FYI I updated your comment. Having "Closes #XXX" will cause it to auto-close that issue when this is eventually merged

**Comment by Eric89GXL** [comment]
@bollu if you really want to see if the docstrings are parsed correctly, add `vispy.visuals.collections` to this list:

https://github.com/vispy/vispy/blob/master/vispy/util/tests/test_docstring_parameters.py#L22

It will probably show some omissions or formatting errors.

**Comment by Eric89GXL** [comment]
Also keep in mind you can run tests on your own computer like:
```
$ python make test nobackend
$ python make test flake
$ python make test pyqt4
$ python make test examples
$ ...
```
Or you can run individual files with:
```
$ nosetests vispy/util/tests/test_docstring_parameters.py
```
or
```
$ py.test vispy/util/tests/test_docstring_parameters.py
```

**Comment by bollu** [comment]
Ah, I wasn't aware of the ```py.test _``` feature. Will use from now on.

**Comment by Eric89GXL** [comment]
Yeah having to wait for Travis is painful during development, I try to only use it once I have something that I think works

**Comment by Eric89GXL** [comment]
This can be done if/when collections get integrated with `visuals`

**Pull request closed without merging**
