### PR TITLE
Fix oscilloscope demo without pyaudio installed

### PR DESCRIPTION
**Pull request by QuLogic**
See #1025.

I'm still seeing a `RuntimeError: OpenGL got errors (glTexImage2D): GL_INVALID_VALUE` though.

### CODE REVIEW

**Comment by QuLogic** [comment]
Ah, `GL_MAX_TEXTURE_SIZE=8192`, but the `ScrollingImage` is 10000. With 8000 it runs, but the top image is empty...

**Comment by QuLogic** [comment]
Oh, the top image works if you input _real_ data. Maybe the non-`pyaudio` sample data should be tweaked a little so it does show up there.

**Comment by Eric89GXL** [comment]
So does this work for you now with and without using `pyaudio`?

**Comment by QuLogic** [comment]
Yea, now the non-`pyaudio` looks like this (I stuck in a sinusoid in there for something interesting):
screenshot from 2015-07-28 18-57-20

**Comment by Eric89GXL** [comment]
Works great, thanks @QuLogic

**Pull request merged**
