### PR TITLE
Allow using gloo without vispy.app again

### LINKED ISSUE #757: gloo cannot be used without a canvas?
The discussion on the list seems to indicate this is the case:

https://groups.google.com/forum/#!topic/vispy/L1EFzNreMgA

@almarklein is there a workaround? Can we tell it somehow not to use features of `Canvas`? It seems like we broke orthogonality a bit with the GLIR code. If there is already a way to do this, then we should fix the `assert` statement with a more informative error saying how to use `gloo` outside the `app` system.

### PR DESCRIPTION
**Pull request by almarklein**
issues: closes #757

Better error message, and a class to help use gloo without an `app.Canvas`.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
Ahh good, I started working on this but didn't get very far.

**Comment by almarklein** [comment]
Example code to use it (in the original code posted in the mailing list, there was no call to `gloo.clear()` or to `SwapBuffers()`:

    import wx
    import numpy as np
    from vispy import gloo
    from wx.glcanvas import GLCanvas,GLContext
    
    c = gloo.context.FakeCanvas()
    
    class TestFrame(wx.Frame):
        canvas = None
        _ini = False
        def __init__(self):
            wx.Frame.__init__(self, None, -1, "Vispy Test",
                            wx.DefaultPosition, size=(500, 500))
    
            self.canvas = GLCanvas(self,attribList=[ wx.glcanvas.WX_GL_RGBA, 
                                                    wx.glcanvas.WX_GL_DOUBLEBUFFER,
                                                    wx.glcanvas.WX_GL_DEPTH_SIZE, 24 ])
            self.glcontext = GLContext(self.canvas)
            
            self.canvas.Bind(wx.EVT_PAINT,self.onPaint,self.canvas)
                    
            sz = wx.BoxSizer(wx.VERTICAL)
            sz.Add(self.canvas,1,wx.EXPAND)
            self.SetSizer(sz)
                    
            MenuBar = wx.MenuBar()
            file_menu = wx.Menu()
            file_menu.Append(wx.ID_EXIT, "&Quit")
            self.Bind(wx.EVT_MENU, self.on_quit, id=wx.ID_EXIT)
            #self.Bind(wx.EVT_SIZE,self.onSize,self)
            MenuBar.Append(file_menu, "&File")
            self.SetMenuBar(MenuBar)
        
        def onPaint(self,e):
            dc = wx.PaintDC(self)
            self.canvas.SetCurrent()
            if not self._ini:
                gloo.set_state(clear_color='blue', blend=True,
                        blend_func=('src_alpha', 'one_minus_src_alpha'))
                self._ini = True
            gloo.clear()
            c.context.flush_commands()
            self.canvas.SwapBuffers()
    
        def on_quit(self, event):
            self.Close(True)
    
    if __name__ == '__main__':
        myapp = wx.App(0)
        frame = TestFrame()
        frame.Show(True)
        myapp.MainLoop()

**Comment by Eric89GXL** [comment]
LGTM. Any point in adding a test that at least uses the functionality? Maybe with a dummy `gl` backend so that it can run without actually having a canvas?

**Comment by almarklein** [comment]
added test

**Pull request merged**
