### PR TITLE
BUG: changed image_tester so it doesn't try to overwrite frozen classes

### LINKED ISSUE #1147: `--vispy-audit` broken after adding freezing into Vispy
the `ImageTester` tries to attach a `self.grid` after calling `super`'s init. 

Error log on using `--vispy-audit`:

```
../../anaconda/lib/python3.4/site-packages/numpy/testing/decorators.py:146: in skipper_func
    return f(*args, **kwargs)
vispy/scene/cameras/tests/test_perspective.py:49: in test_perspective_render
    max_px_diff=200)
vispy/testing/image_tester.py:140: in assert_image_approved
    _get_tester().test(image, std_image, message)
vispy/testing/image_tester.py:65: in _get_tester
    tester = ImageTester()
vispy/testing/image_tester.py:296: in __init__
    self.grid = self.central_widget.add_grid()
vispy/util/frozen.py:16: in __setattr__
    'attributes' % (key, self))
E   AttributeError: 'grid' is not an attribute of class <ImageTester (PyQt4) at 0x1091780f0>. Call "unfreeze()" to allow addition of new attributes
========================================================== 1 failed in 1.19 seconds ==========================================================
```

So, using `--vispy-audit` causes Vispy to fail inside `ImageTester`

### PR DESCRIPTION
**Pull request by bollu**
Fixes #1147 

Should I add a test for `image_tester` as well? (I see where this is going - "who will watch the watchers").

### CODE REVIEW

**Comment by bollu** [comment]
@Eric89GXL - Question on git usage. I need this change to work on `cassowary_constraints`, but the diff will show this (unrelated) change with Vispy until this branch is merged. What's the "right way" to use this change until it has been merged in another branch?

**Comment by Eric89GXL** [comment]
If you expect this to be merged before the other PR (reasonable assumption) I'd rebase that branch off of this one.

**Comment by Eric89GXL** [comment]
Changes LGTM, I guess we haven't used the tester since adding the freezing functionality. Whoops!

**Comment by Eric89GXL** [comment]
I wouldn't worry about tests. It's possible to write them, but this is really an interactive developer tool, so it's easier to fix through use than unit tests, and we don't really endanger user experiences by not testing it thoroughly.

**Comment by campagnola** [comment]
Thanks @bollu!

**Pull request merged**
