### PR TITLE
Fix functionality tests on Intel and software GL.

### LINKED ISSUE #649: gloo.gl.tests.test_functionality._draw1 fails
Tested on Ubuntu 14.04 and Intel GPU (the test passes on the NVIDIA GPU).

```
======================================================================
FAIL: Test pyopengl GL backend for full functionality.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cyrille/anaconda/envs/py27/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/data/git/vispy/vispy/testing/_testing.py", line 180, in skipper
    return f(*args, **kwargs)
  File "/home/cyrille/anaconda/envs/py27/lib/python2.7/site-packages/numpy/testing/decorators.py", line 146, in skipper_func
    return f(*args, **kwargs)
  File "/data/git/vispy/vispy/gloo/gl/tests/test_functionality.py", line 59, in test_functionality_pyopengl
    _test_functonality('pyopengl')
  File "/data/git/vispy/vispy/gloo/gl/tests/test_functionality.py", line 96, in _test_functonality
    _draw1()
  File "/data/git/vispy/vispy/gloo/gl/tests/test_functionality.py", line 507, in _draw1
    _check_result()
  File "/data/git/vispy/vispy/gloo/gl/tests/test_functionality.py", line 547, in _check_result
    assert_equal(pix1, (0, 0, 0))
AssertionError: Tuples differ: (32, 32, 32) != (0, 0, 0)

First differing element 0:
32
0

- (32, 32, 32)
+ (0, 0, 0)
```

### PR DESCRIPTION
**Pull request by QuLogic**
The attribute `a_1` is assigned generic vertex attribute 0, which has some magical properties on legacy desktop GL. By reversing the order, it no longer has such assignment, and works like any other attribute. The new first attribute `a_4` is not modified in the same way as `a_1`, and thus does not suffer due to the magical properties of index 0.

I also fixed a minor typo.

Fixes #649. CC @rossant who was also seeing this issue.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
Thanks @QuLogic, I'll merge this once the CIs come back happy.

**Comment by QuLogic** [comment]
So it looks like it's broken the 2.7 build, but why? It seems like an attribute is magically unset again... Very strange.

**Comment by Eric89GXL** [comment]
Hah! It looks like the fix you used to make things work on Intel hardware broke them on Mesa GL (what Travis uses for rendering).

**Comment by QuLogic** [comment]
I tried with `LIBGL_ALWAYS_SOFTWARE` to try out Mesa only, but I guess that's not quite the same.

Anyway, let's try a different tactic, then.

**Comment by Eric89GXL** [comment]
Fix LGTM. I assume tests pass for you @QuLogic? If so, good to merge from your end?

**Comment by QuLogic** [comment]
Yep, works for me on all backends I could try.

**Comment by Eric89GXL** [comment]
Thanks for solving a long-standing mystery @QuLogic. Had any other issues you've noticed with your Intel hardware thus far?

**Comment by QuLogic** [comment]
There's two more issues with Qt5; not sure if Intel-specific, though. I'll open a new issue for them.

**Comment by Eric89GXL** [comment]
I think you reported your system somewhere but remind me, are you on Ubuntu? I run that on my workstation so I think I should be able to test PyQt5 there.

**Comment by QuLogic** [comment]
Nope, on Fedora 22.

**Pull request merged**
