### PR TITLE
Fix OpenGL to ctypes type mapping

### PR DESCRIPTION
**Pull request by cgohlke**
See https://www.khronos.org/opengl/wiki/OpenGL_Type

### CODE REVIEW

**Comment by djhoese** [comment]
Interesting. Thanks. I don't think I've ever actually run this code myself. And just to clarify, this is functionally the same (c_int versus c_ssize_t) in most cases/systems, right?

**Comment by jni** [comment]
My interpretation is the same as yours @djhoese: resolving to the same hardware type in most systems, meaning it masks a logic error in most systems. =)

**Comment by djhoese** [comment]
@kmuehlbauer you recently played with the codegen, any concerns about this?

**Comment by kmuehlbauer** [comment]
We would need to rerun the codegen to make this permanent. Should this be committed to this PR?

**Comment by djhoese** [comment]
Probably. Give me a sec. I'll do it since it should be merged with the changes on master from a couple days ago.

**Comment by djhoese** [comment]
My browser shows one of two travis tasks (?) is queued but when I click on it it all passes. Thanks @cgohlke. Merging now.

**Pull request merged**
