### PR TITLE
Fix for shared_context.py  in /examples/tutorial/app/

### PR DESCRIPTION
**Pull request by davidruffner**
The Text object from vispy.scene.visuals did not accept a list of parents. I'm not sure if that is the whole point of this file. But I made it work by adding two Text objects each with one parent scene.

Being able to integrate Vispy into a PyQt or PySide app will be very useful.

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@davidruffner It's not really clear to me what you want to achieve. Do you want to integrate a vispy (scene, canvas, plot) in a PyQt app? There are several examples showing this, like https://github.com/vispy/vispy/blob/master/examples/basics/scene/isocurve_for_trisurface_qt.py. 

Or are you interested in using **shared_context**? AFAIR, the example you are referring is currently broken, but I do not remember the details. It is most likely connected to multiparenting. @Eric89GXL do you have the details of shared context and  multiparenting at hand?

**Comment by davidh-ssec** [comment]
I definitely want to here if Eric or other original maintainers know what happened with this example. I'm not sure I agree with this solution for fixing it since I think the original intention was to show how a Visual could be shared between two canvases with a shared context...I think. The proposed changes don't seem to take advantage of the shared context at all.

**Comment by davidruffner** [comment]
@kmuehlbauer @davidh-ssec Thanks for following up. Yes, I'm interested in integrating vispy elements inside a PyQt app. Thanks for the example that you shared. That's a great starting point.

I think you are right that my proposed changes don't address the problem with sharing a Visual between two canvases with a shared context. I'm not sure yet how to make that work. Should I close this pull request?

**Comment by kmuehlbauer** [comment]
@davidruffner Glad the example is useful for your application. If more questions arise, please open another issue. Let's wait for @davidh-ssec to close this one here.

@davidh-ssec For discussing shared context we might use #862.

**Pull request closed without merging**
