### PR TITLE
When gloo object dies, delete associated GPU object

### PR DESCRIPTION
**Pull request by almarklein**
This should fix some memory issues.

### CODE REVIEW

**Comment by almarklein** [comment]
Hopefully fixes #771 and/or #735

**Comment by campagnola** [comment]
Don't need GlirQueue._count_for_cleanup anymore?

**Comment by almarklein** [comment]
> Don't need GlirQueue._count_for_cleanup anymore?

yes, done. I forgot to run pyflakes :/

**Comment by Eric89GXL** [comment]
I get segfaults on this branch :(

**Comment by Eric89GXL** [comment]
They seem rare-ish, though -- maybe it's due somehow to me clicking on some windows when they pop up or something. I'll merge if Travis is happy.

**Comment by almarklein** [comment]
I just tested, and you can now create new  programs/buffers in your draw callback, and the memory stays flat (rather than filling the memory and making my machine logout like it just did when I disabled the delete).

**Comment by Eric89GXL** [comment]
Excellent, thanks!

**Pull request merged**
