### PR TITLE
ENH: Text and console using doc coord sys

### PR DESCRIPTION
**Pull request by Eric89GXL**
@nippoo see if this works.

Closes #511.

### CODE REVIEW

**Comment by nippoo** [comment]
this gets the @nippoo stamp of approval. nice work!

**Comment by rossant** [comment]
pro-tip: add `?w=1` at the end of the PR's URL to remove whitespace diffs.

**Comment by nippoo** [comment]
Yeah, console works great!

**Comment by Eric89GXL** [comment]
@almarklein ready for review/merge. (AppVeyor is being slow, but Travis is happy.)

**Comment by nippoo** [comment]
Looks good to me now :)

**Pull request merged**
