### PR TITLE
Vectorize MeshData vertex normals computation

### PR DESCRIPTION
**Pull request by asnt**
Suggestion to extend https://github.com/vispy/vispy/pull/2433 with tests, clarification of documentation and some formatting.

### CODE REVIEW

**Comment by djhoese** [comment]
Ok so this is #2433 with tests?

@soraxas how does this look to you?

**Comment by soraxas** [comment]
Yep the code LGTM.

Unit test seems straightforward although it didn't quite test much of the edge cases. Should perform sufficient sanity check though.

**Comment by djhoese** [comment]
Great. @asnt do you think these need any other tests?

**Comment by asnt** [comment]
> Great. @asnt do you think these need any other tests?

Not sure.
What are the possible edges cases? What comes to mind:
- Degenerate triangles (i.e. collinear or coinciding vertices) having undefined normals.
- Distance between vertices close to machine epsilon creating numerical errors: inaccurate or wrong normals.
These are not handled in the current code. Not sure we want this handled at this level of abstraction.

**Comment by asnt** [comment]
Same issue: https://github.com/vispy/vispy/pull/2069

**Comment by djhoese** [comment]
I want this PR and all the related ones to stop weighing on me so I'm going to merge this and anything that breaks we can fix later. We've spent too much time trying to get a perfect PR for this optimization and I think this is the closest we've gotten. I think after this then @asnt can work on #2098 to clean up the code a bit (if you want).

**Pull request merged**
