### PR TITLE
Different method of associating glir queues (for better performance)

### PR DESCRIPTION
**Pull request by campagnola**
Ready for review/merge.

This resolves a performance issue where scenes with a large number of visuals were visiting `GlirQueue.clear()` thousands of times per draw.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
Can you comment briefly on what it does? Maybe by commenting on / docstringing the `_GlirQueueShare` class? Thousands of time per draw is pretty rough indeed.

Have you tried this out with the IPython WebGL backend to see if it works? If not I can verify it before merging.

**Comment by campagnola** [comment]
Working on docstring updates. Please do check ipython, thanks!  (it always seems to take me several minutes to get it up and running again)

**Comment by campagnola** [comment]
Basically: in the existing implementation, a graph of dependencies is set up that links objects like `context -> program -> texture`. Each object has its own queue of glir commands, which means that to flush the entire set of commands for a context, you must recursively search the entire tree for stray commands (and this flush occurs once per program draw). 

This PR changes the flow such that, once objects are connected in the graph, they all share the same command queue and it is no longer necessary to search the tree.

**Comment by Eric89GXL** [comment]
So with this new approach is it possible that you might now get multiple threads putting calls into the same queue out of order, whereas previously the order would have been guaranteed (since it the commands would have been extracted from each object in the tree by the drawing thread)? I'm not sure if it matters if this is the case, but I want to know for future reference if we should keep this in mind.

**Comment by campagnola** [comment]
Yes, that could change the order of commands (and we would also need to add a lot of locking to make everything thread safe). I had actually added some code that marked each command based on the order it was generated and sorted before parsing, but ultimately it turned out to be unnecessary.

**Comment by Eric89GXL** [comment]
WebGL appears to work just as well, and tests pass. I trust you there is a performance benefit :)

**Comment by Eric89GXL** [comment]
Thanks. Did you need this for your big PR, or did you just notice this could be split off into a bite-sized PR?

**Comment by campagnola** [comment]
It was something I fixed in the PR but broke it off because I knew it would need a lot of testing and didn't depend on the visual/scenegraph changes (and the tests don't run so well in the PR).

**Comment by almarklein** [comment]
Does this also hold up when *changing* the topology of a scene graph? E.g. when a visual is moved to another canvas? Do changes that have been applied to the visual propagate to the correct parser in this case?

**Comment by campagnola** [comment]
No, this would end in catastrophe by merging together the queues of two different contexts. That will need to be dealt with at some point, but I think it will take a lot of work (beyond the effects of this PR) to make visuals usable on more than one canvas.

**Comment by almarklein** [comment]
Ok, and what about changing the topology where just one context is involved?

**Comment by campagnola** [comment]
If there is only one context, then the topology is irrelevant--all GlirQueues should (eventually) become associated and will share a single underlying queue of glir commands.

**Pull request merged**
