### PR TITLE
AppVeyor: use ci-helpers to fix build issues

### PR DESCRIPTION
**Pull request by astrofrog**
This is a shot in the dark - currently AppVeyor fails with:

```
pip install -q pytest-cov
Traceback (most recent call last):
  File "C:\Python34-conda64\Scripts\pip-script.py", line 3, in <module>
    import pip
  File "C:\Python34-conda64\lib\site-packages\pip\__init__.py", line 14, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "C:\Python34-conda64\lib\site-packages\pip\utils\__init__.py", line 23, in <module>
    from pip.locations import (
  File "C:\Python34-conda64\lib\site-packages\pip\locations.py", line 17, in <module>
    USER_CACHE_DIR = appdirs.user_cache_dir("pip")
  File "C:\Python34-conda64\lib\site-packages\pip\utils\appdirs.py", line 36, in user_cache_dir
    path = os.path.normpath(_get_win_folder("CSIDL_LOCAL_APPDATA"))
  File "C:\Python34-conda64\lib\site-packages\pip\utils\appdirs.py", line 179, in _get_win_folder_from_registry
    import _winreg
ImportError: No module named '_winreg'
Command exited with code 1
```

so I want to see if explicitly making sure pip is up-to-date resolves the issue.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
Well that's silly :) Feel free to merge if it makes AppVeyor happy

**Comment by astrofrog** [comment]
That doesn't help, but I just pushed another change instead that just uses conda to install pytest-cov instead of pip. Should be a sufficient workaround.

**Comment by Eric89GXL** [comment]
That's a better way to get `pytest` anyway, conda packages should be preferred when available

**Comment by Eric89GXL** [comment]
Great, another cryptic error!

**Comment by astrofrog** [comment]
I think it's a conda issue, I've opened an issue here: https://github.com/ContinuumIO/anaconda-issues/issues/794

**Comment by astrofrog** [comment]
@Eric89GXL - I haven't got to the bottom of this, but it seems that switching to ci-helpers to manage the conda environment (https://github.com/astropy/ci-helpers) fixes the problem. The ci-helpers are intended for use by any project, not just Astropy packages, so I don't think there's much downside to switching to that. We centralize any fixes that have to be made to keep things working with AppVeyor and Travis.

If you are happy going ahead with this, I can later also open a pull request to use ci-helpers to simplify the Travis configuration too.

**Comment by Eric89GXL** [comment]
Sounds good to me

**Comment by Eric89GXL** [comment]
Thanks @astrofrog

**Pull request merged**
