### PR TITLE
FIX: fix test/coverage issues

### PR DESCRIPTION
**Pull request by kmuehlbauer**
- keep import_dir
- use cwd only for coverage data

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
Seems, that this is not an easy one. Obviously the `cwd` is needed in the subprocess-call to find some functions.

**Comment by kmuehlbauer** [comment]
see #1571 for background

Suggestions appreciated!

**Comment by djhoese** [comment]
Any new ideas on this? Need me to play with something?

**Comment by kmuehlbauer** [comment]
@djhoese Unfortunately, no new ideas. All I found is described in #1571. We have a problem with testing machinery picking up other *site-packages* (eg. *numpy*) in certain cases. The changes proposed in this PR don't help.

**Pull request closed without merging**
