### PR TITLE
FIX: Raise error for 64-bit float

### LINKED ISSUE #691: Update installation instructions: propose Anaconda as the recommended Python distribution

### LINKED ISSUE #711: Instructions for testing VisPy canvas on Travis
It would be great to put instructions somewhere detailing how to unit test VisPy visualizations on Travis. Typically, I have a project on GitHub that uses py.test and Travis. One of my tests displays a custom visualization created with VisPy (using `canvas.show(); app.run()`). Running `make test` locally opens a window, which has to be closed manually.

On Travis, I'd like at least the GLIR commands to be emitted, even if they are not interpreted by anything. This will test my data baking logic, for example.

What are the exact steps to make this work correctly on Travis? (putting the steps in this issue's discussion would be enough at first)

### PR DESCRIPTION
**Pull request by Eric89GXL**
Also contains a minor fix for the downloading. Will ping once the CIs are happy.

Closes #691.
Closes #711.

### CODE REVIEW

**Comment by almarklein** [comment]
LGTM, except failing tests

**Comment by Eric89GXL** [comment]
Ready for review/merge from my end. @rossant it touches an issue you had open, want to have a look?

**Comment by rossant** [comment]
LGTM!

**Comment by Eric89GXL** [comment]
@almarklein feel free to pull the trigger, then

**Pull request merged**
