### PR TITLE
Add Linux AArch64 wheel build support

### PR DESCRIPTION
**Pull request by odidev**
Added linux aarch64 wheel build support.
Related to https://github.com/vispy/vispy/issues/2277, @djhoese Could you please review this PR?

### CODE REVIEW

**Review by djhoese — APPROVED** [review]
Thanks for this. It would have taken me and annoyingly long time to figure out the specifics for this.

**Comment by djhoese** [comment]
@odidev Looks like the aarch64 build just hangs.

**Comment by djhoese** [comment]
Ok so it finished but it took 46 minutes instead of the ~7 minutes the other environments take. Any ideas what's going on? Only a couple of the dependencies seemed to require building from source. Oh the `nobackend` tests took two minutes instead of a couple seconds like on the Ubuntu environment.

**Comment by djhoese** [comment]
Ah the wheel for freetype-py had to be built.

**Review by almarklein — APPROVED** [review]

**Comment by djhoese** [comment]
@rougier Do you think you could look at https://github.com/rougier/freetype-py/pull/140 and make a release with that? It would speed up these vispy builds a ton if we could pull in a freetype-py aarch wheel.

**Comment by djhoese** [comment]
Note that the freetype-py wheel changes have been merged. I'd like to wait to merge and release this PR until freetype-py has had a new release with these updated wheels to make sure our tests still pass.

**Comment by djhoese** [comment]
Well the freetype-py release has fallen behind. Going to merge this and start working on a vispy patch release today. PyCascades sprint is Sunday.

**Pull request merged**
