### PR TITLE
passing title as encode('utf-8') in glfwSetWindowTitle

### LINKED ISSUE #1533: GLFW glfw.glfwSetWindowTitle issue
Hello there, 
I am using a library https://github.com/p5py/p5 which is dependent on vispy. When passing a new title as str to glfw.glfwSetWindowTitle only the first letter of the passed string is coming up as the changed title. I was able to find a workaround to this by passing the title by encoding it to utf-8 in
https://github.com/vispy/vispy/blob/0ff2bacef0ec941c039708935a4cbd694ecf02ab/vispy/app/backends/_glfw.py#L327
 like the implementation in
https://github.com/vispy/vispy/blob/0ff2bacef0ec941c039708935a4cbd694ecf02ab/vispy/ext/glfw.py#L483

Now I am confused wether to make a pull request to p5py or vispy about this issue as p5py is accepting title as str. 
Thank You

### PR DESCRIPTION
**Pull request by Gotham13121997**
fixes #1533 .

### CODE REVIEW

**Comment by djhoese** [comment]
@Gotham13121997 Does this work on python 2?

**Comment by djhoese** [comment]
Nevermind, this should be fine on python 2. I'm still confused at why this is needed (why it wasn't seen before), but with an ok from @larsoner I'm fine merging this. You may need to rebase/merge with master to get travis to pass its tests.

**Comment by larsoner** [comment]
>  I'm still confused at why this is needed (why it wasn't seen before)

Sometimes encoding issues only manifest if you have non-ASCII chars. Looks reasonable to me

**Comment by Gotham13121997** [comment]
.encode('utf-8') converts it into bytes. I think we were meant to pass bytes like https://github.com/vispy/vispy/blob/0ff2bacef0ec941c039708935a4cbd694ecf02ab/vispy/ext/glfw.py#L483

I think its related to ctypes.
https://stackoverflow.com/questions/27127413/converting-python-string-object-to-c-char-using-ctypes
Maybe this link can help

**Comment by Gotham13121997** [comment]
@djhoese what is the status on this?

**Pull request merged**
