### PR TITLE
Add HSV<->RGB GLSL functions

### LINKED ISSUE #416: Implement reusable GLSL functions for color space transformations
At least RGB <-> HSV. Put them in `vispy.visuals.glsl`.

### PR DESCRIPTION
**Pull request by rossant**
Closes #416.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
It might be good to check that these actually work. WDYT about doing some computations on the CPU using `Color`/`ColorArray`, then also plotting the result using a the simplest GLSL you can build around these functions, and checking that the results match?

**Comment by Eric89GXL** [comment]
We can wait to do this later if you have other high-priority things to work on, but we should at least add a comment in the code with an `XXX` or `TODO` saying we should do it at some point.

**Comment by rossant** [comment]
Hmm, that's a possibility, but no high priority IMO. I'm already using these functions and I know they work (and they are used quite a lot apparently). Unit testing them might not make much sense as they're never going to change...

**Comment by Eric89GXL** [comment]
IMO it is not safe to assume that any code will stay fixed -- intentionally or unintentionally, even the simplest of code can get updated, modified, improved, extended, relocated, etc. That being said, I agree tests aren't a high priority here. Maybe I will tackle them later :)

**Comment by rossant** [comment]
Hmm okay makes sense. This can be done later indeed. Shall I add a TODO?

**Comment by Eric89GXL** [comment]
You've convinced me enough, so only bother if you're feeling bored -- otherwise I'll merge once Travis and AppVeyor are happy, even though it seems silly to wait

**Comment by rossant** [comment]
Hold on I'll do it

**Comment by rossant** [comment]
No prob with waiting for the green button

**Comment by rossant** [comment]
Ready to merge

**Comment by Eric89GXL** [comment]
Thanks for the changes and reminder, I got side-tracked

**Pull request merged**
