### PR TITLE
switch to newer python for ci

### PR DESCRIPTION
**Pull request by brisvag**
As discussed in the monthly meeting, we're switching to newer python for CI. I'm not sure how the workflows work, so this is likely to be completely wrong as a first attempt :P

### CODE REVIEW

**Comment by brisvag** [comment]
@djhoese was I supposed to do something different or am I on the right track?

**Comment by djhoese** [comment]
This is the start of the changes. The website environment has to be updated too and then I forget what the other failure was about. I'll look when I have more time later.

**Comment by djhoese** [comment]
Very strange build issues on the PyQt6 Python 3.10 environment:

```
 Encountered problems while solving:
  - nothing provides freetype 2.5* needed by pillow-3.2.0-py27_0
```

**Comment by brisvag** [comment]
Yeah... that py27 is particularly suspicious! Does that mean that somehow the wrong pillow is being installed? Or are we actually using python 27 somehow?

**Comment by djhoese** [comment]
Ok so the newer github actions didn't fix anything in the Qt6 environment. I now just pushed a commit that removes the version restriction on freetype for the "full" environment. Let's see what happens.

**Comment by djhoese** [comment]
It's working!

**Comment by djhoese** [comment]
Looks good to me! Merging...

**Comment by brisvag** [comment]
Always nice coming back to solved problems :smile:

**Pull request merged**
