### PR TITLE
Added shader preprocessor in ModularProgram

### PR DESCRIPTION
**Pull request by rossant**
* The `#include` preprocessor was only handled on `Program` and not `ModularProgram`. This fixes it.
* `#include` now also searches in a list of paths provided by the list `vispy.config['include_path']`
* Added color space transformation shader in GLSL library

### CODE REVIEW

**Comment by rossant** [comment]
Awaiting for Travis. Ready for review/merge.

**Comment by almarklein** [comment]
LGTM

**Comment by rossant** [comment]
Actually hold on, I'd like to do something else in this PR.

**Comment by rossant** [comment]
OK this time this is ready for review/merge. @almarklein @Eric89GXL

**Comment by Eric89GXL** [comment]
LGTM as well, I always like better error messages :)

**Pull request merged**
