### PR TITLE
Use meshio fall back for reading and writing mesh files

### LINKED ISSUE #1817: meshio for i/o
Main author of [meshio](https://github.com/nschloe/meshio) here.

meshio can read a large number of formats which are applicable for vispy, I think it would be a good match for meshio.

### PR DESCRIPTION
**Pull request by nschloe**
A rather unintrusive introduction of meshio into `read_mesh`. One could go further and have all i/o handled by meshio; obj and stl readers are in place. I didn't want to stretch it too far for this first PR though.

What works now:
```python
import vispy.io

verts, faces, _, _ = vispy.io.read_mesh("triceratops.vtu")
```
with all meshio-supported formats (there are around 30) _if_ meshio is installed and the mesh does in fact contain triangles.

Fixes #1817.

### CODE REVIEW

**Comment by djhoese** [comment]
Awesome! I don't remember if there are tests for this and I need to update the tests to not use python 2.7, but could you look at adding some if there aren't already? At the very least the CI environments probably need meshio to be installed.

**Comment by nschloe** [comment]
I've added meshio writing and a test now. Locally it works fine, let's see what the CI says.

**Comment by nschloe** [comment]
I'll need to install meshio, but I don't know where to best to this.

**Comment by djhoese** [comment]
Here: https://github.com/vispy/vispy/blob/master/azure-pipelines.yml#L14

Here: https://github.com/vispy/vispy/blob/master/appveyor.yml#L13

And to each one of the CONDA_DEPENDENCIES in here: https://github.com/vispy/vispy/blob/master/.travis.yml#L17

**Comment by nschloe** [comment]
Well, that wasn't quite it.

**Comment by djhoese** [comment]
I'm out of the office for the day but I did just merge something into master to fix some tests. Besides your dependency stuff, that may be a good thing to merge.

**Comment by nschloe** [comment]
I don't see anything in master right now, but yeah, there's no rush here anyway.

**Comment by djhoese** [comment]
Ah I see you already merged master in. Otherwise, here is one error I'm seeing:

```
―――――――――――――――――――――――――――――――― test_wavefront ――――――――――――――――――――――――――――――――

../../../miniconda/envs/test/lib/python3.7/site-packages/meshio/_helpers.py:122: in write

    writer = _writer_map[file_format]

E   KeyError: 'foo'

During handling of the above exception, another exception occurred:

vispy/io/tests/test_io.py:25: in test_wavefront

    assert_raises(ValueError, write_mesh, fname_out, *mesh1, format='foo')

vispy/testing/_testing.py:74: in assert_raises

    func(*args, **kwargs)

vispy/io/mesh.py:121: in write_mesh

    mesh.write(fname, file_format=format)

../../../miniconda/envs/test/lib/python3.7/site-packages/meshio/_mesh.py:121: in write

    write(path_or_buf, self, file_format, **kwargs)

../../../miniconda/envs/test/lib/python3.7/site-packages/meshio/_helpers.py:126: in write

    file_format, sorted(list(_writer_map.keys()))

E   KeyError: "Unknown format 'foo'. Pick one of ['abaqus', 'ansys', 'avsucd', 'cgns', 'dolfin-xml', 'exodus', 'flac3d', 'gmsh', 'gmsh22', 'h5m', 'mdpa', 'med', 'medit', 'nastran', 'neuroglancer', 'obj', 'off', 'permas', 'ply', 'stl', 'svg', 'tecplot', 'tetgen', 'ugrid', 'vtk', 'vtu', 'wkt', 'xdmf']"
```

**Comment by nschloe** [comment]
No idea why these errors should occur. Perhaps the tester got an old meshio version? Where can I see what version is installed? How to rerun the tests?

**Comment by djhoese** [comment]
You, as a non-admin to this project, can't restart tests without making a commit. If you'd like them restarted let me know which ones. You can see the output of the tests by clicking on "Details" (I would start with Travis), going to the failing environment and scrolling through the log.

Note: By putting `meshio` in the CONDA_DEPENDENCIES on travis it is going to load them from conda-forge. Your package's documentation said this was possible. If the newest version is not available then that could be the problem.

**Comment by nschloe** [comment]
It's available on conda-forge now, but perhaps (since the release was so young) not at the time of testing. I guess I just make a dummy commit.

**Comment by nschloe** [comment]
Travis now passes, but some tests still seem to be missing meshio installed.

**Comment by djhoese** [comment]
In the azure pipelines file, try moving the meshio dependency to `CIBW_TEST_REQUIRES`.

**Comment by nschloe** [comment]
Success! :tada:

**Comment by djhoese** [comment]
Thanks again. I think this is the start of some good functionality using meshio.

**Pull request merged**
