### PR TITLE
Consistently use "method" instead of "style" and "mode"

### PR DESCRIPTION
**Pull request by campagnola**
Changed mode=>method for line visual and style=>method for volume visual

### CODE REVIEW

**Comment by almarklein** [comment]
You missed some.

**Comment by campagnola** [comment]
@Eric89GXL, any idea if this error is ignorable? I can't reproduce it locally.

**Comment by Eric89GXL** [comment]
I started seeing this early this week, with no real changes to how we do FreeType. I'll probably need to add some sort of exception. I'll try to reproduce it when I'm back on Linux on Monday, and if I can't succeed, I'll find a way to skip it.

I'll review this PR shortly, too.

**Comment by Eric89GXL** [comment]
BTW sometimes restarting the test "fixes" the problem, which I've done here.

**Comment by Eric89GXL** [comment]
Oh good, I've actually changed "style" -> "symbol" for the `MarkerVisual` in my plotting PR, so I think we'll be complementary instead of overlapping. Hooray, fewer merge conflicts!

Looking at the `git grep` it looks like you got the rest for `LineVisual` and `VolumeVisual`, so I'm happy to go ahead and merge this and clean up anything else if necessary in the plotting PR. It looks like you need a rebase, though, since this can't automatically be merged.

**Pull request closed without merging**
