### PR TITLE
Fix gallery generation

### PR DESCRIPTION
**Pull request by davidh-ssec**
Includes fixes to `scrolling_plots.py`. See commit messages for details.

### CODE REVIEW

**Comment by davidh-ssec** [comment]
@larsoner I don't know if it'll complain about that warning. It complains when the vispy logger puts out a warning, but not so sure about numpy warnings. This warning is semi-unavoidable without copying arrays and doing extra NaN or 0 checks. It is only happening because the canvas isn't fully set up from what I can tell. It is better than the complete failure it was doing before.

**Comment by larsoner** [comment]
True, feel free to merge once the CIs are happy

Are you planning to add all examples to the website somewhere/somehow?

**Comment by davidh-ssec** [comment]
> Are you planning to add all examples to the website somewhere/somehow?

Not until the release is out unless you feel strongly otherwise. Making websites look good is not my strong suit and I'd rather not waste a ton of time putting up examples. Maybe I'll feel differently this weekend, but there is also no reason it can't be added to the website after the PyPI release is done.

**Comment by larsoner** [comment]
Sounds good to me

**Comment by davidh-ssec** [comment]
Current OSX backlog on travis: 540 jobs

We'll have to wait.

**Pull request merged**
