### PR TITLE
windows standalone

### PR DESCRIPTION
**Pull request by yhql**
Implements #1266
 On windows, install vispy with glfw3, freetype253, requiring MSVC2013, and also copy OpenSans-Regular. On other platforms, do nothing.
 This provides 'corporate' installation which does not require internet connection to vispy's github repository to make it usable.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
I am -1 on packaging more binaries, as maintaining them can add substantial maintenance burden. Does it work in 64 bit, 32 bit, across OSes, does it require a runtime, etc. are just a subset of issues that can come up. It would probably be better as a separate package, or as a `zip` file saved somewhere that people could optionally download when downloading VisPy

**Comment by yhql** [comment]
Thanks for your comment ! I understand the problem, however I wanted to avoid the connections that VisPy does when Freetype and OpenSans are nowhere to be found on the target machine, and also provide a default backend.
As Vispy is not tied or dependent on a specific-backend, I thought it wouldn't be a bad thing to just use one of a specific version and for a specific OS.
My modifications were intended for win32 and x64 only, as this is the type of environment Vispy's connections will be blocked (corporate network). This would limit the maintaining.

Also, as freetype and OpenSans are downloaded and stored at different places, I could not find an easy way to provide those with the current architecture. Your suggestion of having a separate package means VisPy should be modified in order to look in an optional folder for those files it's missing, before looking anywhere else. Would that be a good modification to bring ?

(also while I'm here : thanks to you and your 'colleagues' for this module :) a lot)

**Comment by Eric89GXL** [comment]
Point taken. This would also potentially take care of the issues in #1327. @stxlvt would bundling these things help?

**Comment by stxlvt** [comment]
@Eric89GXL: yes, I think bundling is an acceptable solution. :-)

**Comment by davidh-ssec** [comment]
@Eric89GXL @yhql I'm just now finding this issue. Is there a reason these libraries need to be bundled rather than requiring them to be installed separately? Don't libraries like matplotlib require they be installed separately? Is this too much to ask from vispy users?

**Comment by Eric89GXL** [comment]
> Is there a reason these libraries need to be bundled rather than requiring them to be installed separately?

Because in general Windows (and OSX?) users who do `pip install vispy` will be very unhappy with the result, and we will get a lot of complaints.

**Comment by yhql** [comment]
>  I'm just now finding this issue. Is there a reason these libraries need to be bundled rather than requiring them to be installed separately? Don't libraries like matplotlib require they be installed separately? Is this too much to ask from vispy users?

Actually the problem is that vispy tries to download libraries like freetype by connecting to some repository and managing the connection by itself. This can be a security issue as @stxlvt reported.
Also this means the connection will be blocked by any corporate firewall, and you'll end up trying to get freetype and opensans on your own. (I admit that bundling a backend is not necessary though)
The libraries _could be_ required to be installed separately, but that's not how vispy works right now. 

(also matplotlib is a python module, this is much simpler to install on windows than freetype for example)

**Comment by davidh-ssec** [comment]
> (also matplotlib is a python module, this is much simpler to install on windows than freetype for example)

@yhql I was referring to matplotlib's installation instructions that talk about installing libpng and freetype yourself. https://matplotlib.org/users/installing.html#building-on-macos

**Comment by kmuehlbauer** [comment]
IMHO this is a tradeoff between the sustainability of the detection/search-code, bundling efforts or to document how those libs are to be installed on a per user basis. I'm also wondering if completely unbundling `freetype` and adding as a dependency would be a more sensible way.

**Comment by larsoner** [comment]
We should probably do whatever `matplotlib` and other standard libraries do, which is probably to let `conda` or other packaging managers / maintainers deal with dependencies. IIRC our `freetype` on Windows is just one I built a while ago, and we hope it continues to work, so this could be taken care of simultaneously with #1327.

**Comment by kmuehlbauer** [comment]
@larsoner Yes, [freetype](https://github.com/conda-forge/freetype-feedstock) is already build on `conda-forge` for the three major OS. It would only need to get @rougier 's python-bindings into a conda-recipe https://github.com/rougier/freetype-py/.

**Comment by larsoner** [comment]
We already bundle those:

https://github.com/vispy/vispy/blob/master/vispy/ext/_bundled/freetype.py

**Comment by kmuehlbauer** [comment]
> We already bundle those:

I know. The question is, is this really necessary? I might lack some understanding, but why was this bundled in the first place?

**Comment by larsoner** [comment]
Strictly speaking, no. At one extreme, you could bundle everything (pretty much this PR). At the other extreme, you could eliminate all of `ext` and make a really long `requirements.txt` and set build requirements.

To me getting rid of the downloaded binary blobs is good for maintainability. But getting rid of the bundled requirements doesn't buy us much in terms of maintainability, at least not enough to offset the increased user install burden.

**Comment by kmuehlbauer** [comment]
> To me getting rid of the downloaded binary blobs is good for maintainability. But getting rid of the bundled requirements doesn't buy us much in terms of maintainability, at least not enough to offset the increased user install burden.

Yes, that was what I meant by **tradeoff** a few comments above. If I get this correctly, we now try to eliminate the `downloading` by either bundling or making a dependency whichever suits us best.

**Comment by djhoese** [comment]
Coming back to this after a couple years: #1664 removed bundled freetype and we now depend on freetype-py, OpenSans has been bundled with vispy now (I don't know when), and glfw is not downloaded automatically and is an external dependency like all other backend dependencies. I still agree with @larsoner that bundling more binaries is a bad idea for maintenance and users should use their own package managers for installing any other dependencies. If you feel that this should still be considered feel free to comment, otherwise I'm closing this.

**Pull request closed without merging**
