### PR TITLE
[WIP] Add a spheres visual

### PR DESCRIPTION
**Pull request by sofroniewn**
This PR would add a spheres visual that could be used to efficiently render many spheres in a single visual, which will have good performance characteristics.

It is based on code in https://github.com/acabrelles/protein-viewer/blob/cc15994453b58a31789b93a9513ef9f087b5ad20/Viewer3d/VisPyViewer.py#L1-L137 from @acabrelles (BSD3 licensed) and an original example from @campagnola.

This PR is missing tests, and should be fleshed out a little before merge, but I'm mainly curious at this point if this is something that people would like added to vispy, and if they have any tips before going further. I've added the code a little to try and resemble the `Markers` visual, which is similar in that it supports points with radii, but it doesn't support any lighting.

Here is a simple script to test the new visual

```python
"""
Create a Spheres Visual
"""
import numpy as np
from vispy import app, scene

# Create canvas and view
canvas = scene.SceneCanvas(keys='interactive', size=(600, 600), show=True)
view = canvas.central_widget.add_view()
view.camera = scene.cameras.ArcballCamera(fov=60)
view.camera.scale_factor = 70

# Prepare data
np.random.seed(57983)
data = np.random.normal(size=(40, 3), loc=0, scale=10)
size = len(data) * [3]
colors = len(data) * ['white']

data = np.concatenate([data, [[0, 0, 0]]], axis=0)
colors.append('red')
size.append(6)

# Create and show visual
vis = scene.visuals.Spheres(data, size=size, color=colors)
vis.parent = view.scene

# Run example
app.run()
```

Screen Shot 2021-03-13 at 6 56 14 PM

## Motivation

A couple of us are considering adding molecular viewing to napari, and in order to do so we'll need to be able to render many spheres and cylinders to represent atoms and their bonds. This PR would let us render many spheres very quickly. cc @alisterburt.

I'd also be very interested if anyone has any tips for the cylinders (happy to discuss in a new issue if so).

## Alternatives

There is a single `Sphere` visual right now based on a `Mesh` visual, and one could make many Spheres using CompoundVisuals, but that would be slow.

One could try and add support for the 3D shading style rendering to the `Markers` visual, but that might cause that file to get very complex.

## Additional Comments

I ultimately will want to use this alongside the other Mesh visuals, possibly in a compound visual, and will want to make sure that the lighting and shading looks good across both for the spheres and the other meshes. I havn't tried combining the visuals yet, but wanted to comment on that too.

### CODE REVIEW

**Comment by sofroniewn** [comment]
## Update

I looked into combining the `Spheres` with the `Mesh` visual a little more in the following example using the `Tube` visual (which is built on `Mesh`)

```python
"""
Create a Spheres Visual
"""
import numpy as np
from vispy import app, scene

# Create canvas and view
canvas = scene.SceneCanvas(keys='interactive', size=(600, 600), show=True)
view = canvas.central_widget.add_view()
view.camera = scene.cameras.ArcballCamera(fov=60)
view.camera.scale_factor = 70

# Prepare data
np.random.seed(57983)
data = np.random.normal(size=(40, 3), loc=0, scale=10)
size = len(data) * [3]
colors = len(data) * ['white']

data = np.concatenate([data, [[0, 0, 0]]], axis=0)
colors.append('red')
size.append(6)

# Create and show visual
vis = scene.visuals.Spheres(data, size=size, color=colors)
vis.parent = view.scene

# Create and show mesh visual
lines = np.array([[data[i], data[-1]]for i in range(len(data)- 1)])
line_vis = []
for line in lines:
    vis2 = scene.visuals.Tube(line, radius=.4)
    vis2.light_dir = (5., -5., 5.)
    vis2.parent = view.scene
    line_vis.append(vis2)

# Run example
app.run()
```

Then I see the following

spheres_with_tube

I notice two things wrong - one is that the lighting direction on the mesh seems to change with rotation, whereas the lighting direction with the spheres is always the same.

The second is that the mesh seems to be always behind the spheres.

**Comment by djhoese** [comment]
Very cool. I suppose the main benefit of this implementation to combining meshes is it should be easier to describe and probably perform better right? I guess I'm wondering why the basic SphereVisual couldn't be expanded to support multiple Visuals (I've never actually looked/tried). Could this be a replacement for the single SphereVisual in the future? Are there features offered by that visual that aren't possible here?

Is there anything that can be learned from some of the molecular viewer examples (that I think were ported from glumpy by @rougier)? Maybe the lighting issues have already been covered there? I'm surprised a little by the weird obstruction/depth issues (better way to refer to this?) where the tube meshes are always behind the spheres because they have the same `set_gl_state` settings. I wonder if it is a draw order thing.

**Comment by sofroniewn** [comment]
> I suppose the main benefit of this implementation to combining meshes is it should be easier to describe and probably perform better right? I guess I'm wondering why the basic SphereVisual couldn't be expanded to support multiple Visuals (I've never actually looked/tried).

Yes that is my intuition, though I havn't benchmarked it. In the SphereVisual you generate the meshes for each Sphere on the cpu first and then pass then to the graphics card. You could definitely generate all of them individually, concatenate them, and then pass them in a single step - that would be much faster than using a CompoundVisual, but I still think it would be much slower than this because of the mesh generation and concatenation.

> Could this be a replacement for the single SphereVisual in the future? Are there features offered by that visual that aren't possible here?

Possibly. The existing SphereVisual allows for a edge_color and a face_color, though I havn't seen what that actually looks like. I think it would be hard to add that to the new SpheresVisual, but I'm not sure if people need that.

Probably the most important thing would be to get the lighting and shading figured out so this new `SpheresVisual` could be used alongside the Mesh visual in the same scene.

**Comment by yxdragon** [comment]
Hi, @sofroniewn , Can you mark every ball with a text 'ID=xxx'? (text have depth, but always on the ball face to us) I want to visualize a DNA structure, and mark every node.  @djhoese that is the billboard feature what I say.

And about meshes utility, we can add an merge_mesh(verts_s, faces_s, colors_s) method, combine the verts, and add offset to the faces. That will be a general solution.
[here](https://github.com/Image-Py/imagepy/blob/master/sciapp/util/meshutil.py) I wrote some creats lines, spheres, merge meshes method. Is it useful? May I add it to vispy.geometry.generation?

**Comment by djhoese** [comment]
Just to keep everything connected. The dashboard issue is https://github.com/vispy/vispy/issues/2062. @yxdragon Feel free to make a pull request.

**Comment by brisvag** [comment]
I have a working implementation in #2204 that should supersede this and fix the remaining issues!

**Comment by sofroniewn** [comment]
Closing this as it will be superseded by #2209 - great work picking this up @brisvag!!

**Pull request closed without merging**
