### PR TITLE
More minor vispy.geometry fixes

### PR DESCRIPTION
**Pull request by FiachAntaw**
I ran into another issue with vispy.geometry on 64-bit python (specifically when creating a MeshData from unindexed vertices), so I went ahead and made all the implicit-width datatypes 32-bit (haven't run into any issues yet).

I also exposed the create_cone function, so all the .generation.create_ methods are now exposed in vispy.geometry with similar default parameters.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
It looks like this breaks a bit of code because of precision:

https://travis-ci.org/vispy/vispy/jobs/51164338

If you change the assert to be `np.allclose(number, 0)` or so instead of `number == 0`, it should fix it.

Don't worry about Travis being angry about style, that's unrelated to your changes.

**Comment by FiachAntaw** [comment]
I tried weakening the assert, but other issues emerged that seemed to come from some precision issue deeper in the algorithm. Looking at the original, working code it seems that the datatype of the point list was getting silently changed from 32-bit to python's native double-precision float on line 84:

```python
self.pts = pts.view(np.float32).reshape(len(pts), 2)
...
newpts = np.empty((self.pts.shape[0]+2, 2), dtype=float)
...
newpts[2:] = self.pts
self.pts = newpts
```

The algorithm doesn't seem to work if newpts is switched to np.float32 or self.pts is initialized to np.float64 and I don't really want to mess with it without understanding the algorithm it's implementing, so I've reverting the change I made to triangulate.py.

**Comment by Eric89GXL** [comment]
@FiachAntaw is this good to go from your end, then? LGTM

**Comment by FiachAntaw** [comment]
Yeah, it's good to go.

**Comment by Eric89GXL** [comment]
Great, thanks for the additional fixes.

**Pull request merged**
