### PR TITLE
Update docs submodule and settings

### PR DESCRIPTION
**Pull request by ghisvail**

### CODE REVIEW

**Comment by Eric89GXL** [comment]
The most common convention is to use `doc/` not `docs/` can you change it (back) to that?

**Comment by Eric89GXL** [comment]
(in the Python packages I've seen anyway)

**Comment by ghisvail** [comment]
sure

**Comment by ghisvail** [comment]
there you go

**Comment by ghisvail** [comment]
hang on, I forgot to revert the second commit

**Comment by ghisvail** [comment]
should be good now, sorry for the noise.

**Comment by Eric89GXL** [comment]
I have no idea why all of a sudden we see these docstring errors, I'm on it

**Comment by Eric89GXL** [comment]
Thanks @ghisvail

**Pull request merged**
