### PR TITLE
Set depth buffer in Volume plane rendering

### PR DESCRIPTION
**Pull request by brisvag**
This PR adds a few lines to set the depth buffer when rendering a volume with the `plane` raycasting mode.

Before/after:

https://user-images.githubusercontent.com/23482191/151813078-d36ce3a3-8d38-4eef-95ae-19709a42c16e.mp4

https://user-images.githubusercontent.com/23482191/151813074-80e989d9-ee5d-4847-bf24-818bb2d8d07d.mp4

### CODE REVIEW

**Review by alisterburt — APPROVED** [review]
Oh I am so so so in love with this 😍 

This solution is slightly wrong, in plane mode the depth should be set to the ray-plane intersection rather than the min/max/iso etc as it is currently - we can fix this here or in a small followup PR, as you prefer!

**Comment by djhoese** [comment]
Also note I'm marking this as a bug fix as it fixes a visual artifact even if it is a new "feature" (depth-wise). I'll plan on including it in the next release today or tomorrow.

**Comment by brisvag** [comment]
> Love it! Is this change worth a new test?

It's a bit tricky to test this one. I'll try to come up with a rendering-based test, let's see what I can do!

**Comment by brisvag** [comment]
Yep, that's what I'm going for, but vispy tests are always tricky to get right :P

**Comment by brisvag** [comment]
@djhoese this test should be good. It fails on main. Hopefully CI agrees (I had issue with canvas sizes doing weird stuff on my local machine before).

**Comment by djhoese** [comment]
You made flake mad:

```
Running flake8... 
vispy/visuals/tests/test_volume.py:295:1: E302 expected 2 blank lines, found 1
vispy/visuals/tests/test_volume.py:307:9: F841 local variable 'plane1' is assigned to but never used
vispy/visuals/tests/test_volume.py:317:9: F841 local variable 'plane2' is assigned to but never used
vispy/visuals/tests/test_volume.py:336:1: E303 too many blank lines (3)
Failed: flake8 failed
```

**Comment by brisvag** [comment]
This is what the test is doing:


https://user-images.githubusercontent.com/23482191/151826922-08a8f315-ea87-4155-a95b-dde4a5e9e801.mp4

And without rotating simply checking that left and right side are the two different colors.

**Comment by djhoese** [comment]
I'm guessing the tests pass locally? Maybe depth testing doesn't work on CI? Or something else?

**Review by almarklein — APPROVED** [review]

**Comment by brisvag** [comment]
Yeah testing vispy on my machine is still completely broken. Most tests don't pass, because the sampled point in the canvas is wrong (probably due to how my window managed sizes windows? Not sure...).

It would be nice if someone else whose machine passes the rest of the tests fixes the one I just added so that the sampled points are correct!

**Comment by djhoese** [comment]
Good news (?) it fails for me too!

**Comment by djhoese** [comment]
Ok I think I fixed it. @brisvag let me know if the changes make sense to you. First, I was getting a warning because `np.zeros` and `np.ones` were defaulting to 64-bit floats. To be explicit I changed them to uint8s. The resulting image when copied to a standalone script was all red on the left and all white on the right. That makes sense I think since the reds colormap goes from all white to all red so an all 1s volume with clims (0, 1) should result in all red. On the grays Volume, the colormap goes from all black to all white so an all 1s volume with clims (0, 1) should result in all white.

**Comment by brisvag** [comment]
Yup, that makes sense. I don't know what I was thinking, nor how it worked on my machine... What a mess :D Thanks for tracking this down!

**Pull request merged**
