### PR TITLE
FIX: Nest triangle and skimage imports

### PR DESCRIPTION
**Pull request by larsoner**
Addressing @cgohlke's [comment](https://github.com/vispy/vispy/issues/1779#issuecomment-561366474).

### CODE REVIEW

**Comment by djhoese** [comment]
One of the travis jobs failed in a new way. I've restarted it. :crossed_fingers:

**Comment by larsoner** [comment]
Pushed a commit to nest our `sklearn` import, too

**Comment by djhoese** [comment]
Has someone made an issue to triangle and the other packages mentioned by @cgohlke about pkg_resources being so slow on large environments? It shouldn't be a huge deal for them (hopefully) to change this.

**Comment by larsoner** [comment]
@djhoese can I kill the 2.7 CI entries in this PR? Probably time to get rid of them anyway

> Has someone made an issue to triangle and the other packages mentioned by @cgohlke 

This is being tracked in https://github.com/napari/napari/issues/758, but the answer seems to be yes. See for example:

https://github.com/drufat/triangle/pull/40

**Comment by djhoese** [comment]
I'd like to include this PR as one more 0.6.x release (it's still 2019 :wink: ) and then we drop python 2.7. If you want to try adding a tolerance to the failing test and see if that passes it that sounds like the easiest solution for now.

**Comment by larsoner** [comment]
All better @djhoese

**Pull request merged**
