### PR TITLE
MIN: add two_qt_widgets in examples/demo/gloo 

### LINKED ISSUE #1298: Multiple OpenGL windows not working
Tested using the latest Github code from today.

The GL tutorial tests (e.g. fireworks.py, cube.py) work fine within a PyQT application. But if you attempt to display two of them simultaneously (two widgets in one app) then both of them break, either corrupted graphics or failure to repaint the widget. Should two GL widgets be possible with vispy?

Attached a simple test app "test.py" that shows the issue. Code is as follows and uses the standard fireworks.py, cube.py examples:

```
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
import cube, fireworks
 
class Form(QWidget):
    def __init__(self, parent=None):
        super(Form, self).__init__(parent)
 
        cube_canvas = cube.Canvas()
        fireworks_canvas = fireworks.Canvas()
        Layout1 = QVBoxLayout()
        Layout1.addWidget(fireworks_canvas.native)
        Layout1.addWidget(cube_canvas.native)
 
        mainLayout = QGridLayout()
        mainLayout.addLayout(Layout1, 0, 1)
        self.setLayout(mainLayout)
        self.setWindowTitle("Vispy")
 
 
if __name__ == '__main__':
    import sys
    app = QApplication(sys.argv)
    screen = Form()
    screen.show()
    sys.exit(app.exec_())

```
[2glviews.tar.gz](https://github.com/vispy/vispy/files/685855/2glviews.tar.gz)

### PR DESCRIPTION
**Pull request by kmuehlbauer**
closes #1298 

Note: This Example uses PyQt4 but this also works with PyQt5

### CODE REVIEW

**Comment by larsoner** [comment]
> Note: This Example uses PyQt4 but this also works with PyQt5

Is it worth adding some `try/except` logic?

Travis is unhappy with the example formatting

**Comment by kmuehlbauer** [comment]
> Travis is unhappy with the example formatting

@larsoner Do you happen to know why?

**Comment by larsoner** [comment]
From here:

https://github.com/vispy/vispy/blob/master/vispy/testing/_runners.py#L236

There needs to be a `canvas` (or similarly-named) variable that the test runner can use to pull a screenshot from.

**Comment by davidh-ssec** [comment]
Or you could put `# vispy: testskip`:

```
----------------------------------------------------------------------
Example demo/gloo/two_qt_widgets.py failed (1):
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<string>", line 21, in <module>
RuntimeError: Bad example formatting: fix or add `# vispy: testskip` to the top of the file.
----------------------------------------------------------------------
```

**Comment by kmuehlbauer** [comment]
> Is it worth adding some try/except logic?

@larsoner We should make this a milestone and try to handle all of Qt4/Qt5 within vispy, if possible.

**Pull request merged**
