### PR TITLE
Added GridMesh visual

### PR DESCRIPTION
**Pull request by inclement**
This PR is the same as the previous one at https://github.com/vispy/vispy/pull/959, which I managed to mess up somehow.

It includes everything from before, plus the final fixes that I never did, plus some small changes to work with changes in vispy in the last few months. So, it should be ready for re-review.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
LGTM, thanks for addressing the last issues. It looks like there is a small problem in the example though, in that the spheres don't occlude one another properly. Do you have that problem, too? Maybe depth testing needs to be turned on for the visual?

**Comment by inclement** [comment]
I don't see any problem with the sphere occlusion, do you have a screenshot of it?

**Comment by Eric89GXL** [comment]
I get one set of spheres always in front even if they aren't supposed to be. But I don't think that's your bug; we have an open issue for that somewhere. Ready for merge from your end, then?

**Comment by inclement** [comment]
Yep, I think it's good to go from my end.

**Comment by Eric89GXL** [comment]
Great, thanks @inclement!

**Pull request merged**
