### PR TITLE
Add shading to SphereVisual

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
#### What does this implement/fix?
The goal of this PR is to enable the `shading` capabilities of the `vispy.visuals.SphereVisual`.

#### Additional information
Some tweaking might be needed, tell me what do you think?

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@GuillaumeFavelier  LGTM so far. I'm a bit unsure with respect to the `gl_state`.

In `MeshVisual` it is set to ```self.set_gl_state('translucent', depth_test=True, cull_face=False)``` and in SphereVisual it is set to ```self.mesh.set_gl_state(polygon_offset_fill=True,                         polygon_offset=(1, 1), depth_test=True)```. @rougier Does the second call override the first settings? Or does this make sense?

I checked with a slightly altered `example/basics/scene/sphere.py` and it works quite well (flat and smooth shading).

**Comment by rougier** [comment]
@kmuehlbauer I'm not sure why the `polygon_offset_fill` and  `polygon_offset` are set. Those are used when you want to draw something over something else. Typically, this is used to draw the border of a cube (first you draw the filled cube, then the outline)

**Comment by kmuehlbauer** [comment]
@rougier The SphereVisual draws a meshed sphere. I think it is to see the mesh structure. So if you do not see any problems using that way of setting gl_state, we can move forward.

**Comment by kmuehlbauer** [comment]
As @rougier seems fine with it, we could move forward. @djhoese Did we have this windows error before? Seems related to sdf_text.

**Comment by djhoese** [comment]
I'm starting the appveyor tests over again for sanity sake. No I have not seen this error before.

**Comment by djhoese** [comment]
@kmuehlbauer is this branch up to date with your recent changes to `master` and the CI environments?

**Comment by kmuehlbauer** [comment]
It's everything in besides the Klein bottle example.

I did not change appveyor setup.

**Comment by djhoese** [comment]
@GuillaumeFavelier do you think you could merge current master in to your branch? I think I've fixed the Windows failures.

**Comment by GuillaumeFavelier** [comment]
yeah, sure. I'll do it right now.

**Pull request merged**
