### PR TITLE
Klein bottle example

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR try to adress #819

The code so far is really basic, feel free to tell me what you think, I'm ready to work on it.
And I'm not even sure where to put the example?

### CODE REVIEW

**Comment by djhoese** [comment]
Nice catch on the division issues. I think putting it in the demo directory is fine. I'm not sure what that was originally for, but it doesn't seem right for any of the other examples directories. Any opinion @kmuehlbauer @larsoner? I have not tested this.

**Comment by kmuehlbauer** [comment]
@GuillaumeFavelier Very nice!

**Comment by kmuehlbauer** [comment]
The abysses of different OS, the hanging indent was catched by macOSX flake8 but not by the linux based install.

**Comment by kmuehlbauer** [comment]
@GuillaumeFavelier The CI waits for your interaction :grin: I'll stop the older running builds.

**Comment by GuillaumeFavelier** [comment]
Ok, I'll keep an eye on it to make it as green as possible.

**Comment by GuillaumeFavelier** [comment]
Apparently, Travis is not happy because of an error in the `basics/plotting/colorbar.py` example.

**Comment by kmuehlbauer** [comment]
Might be spurious. Restarted that test.

**Comment by larsoner** [comment]
I see a seam. Is this actually a mesh definition problem rather than a rendering error (there are also rendering problems, possibly as expected for non-OIT rendering, which is fine):

screenshot from 2019-02-08 13-51-11

**Comment by GuillaumeFavelier** [comment]
I saw nothing wrong when I tried to inspect the geometry but it was less informative than I thought because of the clutter.

Pseudo-wireframe (line_strip)

klein_wireframe

but apparently near the seam, the properties of the normals change:
`gl_FragColor = vec4(v_normal_vec, 1.0);`

klein_normal

**Comment by larsoner** [comment]
Okay so it's just some rendering bug probably in the shading code. Thanks @GuillaumeFavelier

**Pull request merged**
