### PR TITLE
Adding capability to load STL file with read_mesh function.

### PR DESCRIPTION
**Pull request by JPFrancoia**
See https://github.com/vispy/vispy/issues/1425

### CODE REVIEW

**Comment by JPFrancoia** [comment]
Hum...Did the tests fail because of my code ?

**Comment by davidh-ssec** [comment]
No, a new numpy version has broken some of our tests. I'm trying to fix them today.

**Comment by kmuehlbauer** [comment]
We need to add the MIT header and a pointer to the source in the `stl.py`. Didn't manage to respond earlier.

**Comment by davidh-ssec** [comment]
@kmuehlbauer I added that on my merge on the command line. Check out master and let me know if you think I should update it.

**Comment by davidh-ssec** [comment]
https://github.com/vispy/vispy/blob/master/vispy/io/stl.py

**Comment by kmuehlbauer** [comment]
@davidh-ssec Looks good! 👍 Next time, I'll look directly into master, to see the foo 😁.

**Comment by davidh-ssec** [comment]
Normally I would update the PR, but I thought it would be easier to just do the changes locally and push since things needed to be rebased/merged with my fixes in master.

**Comment by JPFrancoia** [comment]
Thanks for the help guys :)

**Pull request merged**
