### PR TITLE
Fix face normal in cube geometry (create_cube function)

### PR DESCRIPTION
**Pull request by asnt**
This seems like a typo.

### CODE REVIEW

**Comment by djhoese** [comment]
Looks like this was identified in 2017 by @VlasenkoDmytro in #1319. I don't see an existing pull request so thanks for fixing this.

**Comment by djhoese** [comment]
Closes #1319

**Comment by asnt** [comment]
> Looks like this was identified in 2017 by @VlasenkoDmytro in #1319. I don't see an existing pull request so thanks for fixing this.

Thanks. I added the same fix to the gloo example mentioned in #1319

**Comment by djhoese** [comment]
Once the CI passes, is this ready for merge?

**Comment by asnt** [comment]
> Once the CI passes, is this ready for merge?

Yes, now ready.

**Pull request merged**
