### PR TITLE
Add website building to travis tests

### PR DESCRIPTION
**Pull request by djhoese**
This is an attempt to get travis to build the vispy website and upload it to the vispy-website repository. It was recommended that we look at doctr for handling the upload and deploy key handling (https://github.com/drdoctr/doctr). One nice thing about that would be this extension that allows us to have multiple versions like readthedocs allows (https://github.com/goerz/doctr_versions_menu).

I can't promise I'll get to it (maybe a good hacktoberfest issue), but here are the current issues I see when I build the site locally:

```
/home/davidh/repos/git/vispy/_website/conf.py:352: RemovedInSphinx40Warning: The app.add_stylesheet() is deprecated. Please use app.add_css_file() instead.
  app.add_stylesheet('css/font-mfizz.css')
/home/davidh/repos/git/vispy/_website/conf.py:353: RemovedInSphinx40Warning: The app.add_stylesheet() is deprecated. Please use app.add_css_file() instead.
  app.add_stylesheet('css/font-awesome.css')
/home/davidh/repos/git/vispy/_website/conf.py:354: RemovedInSphinx40Warning: The app.add_stylesheet() is deprecated. Please use app.add_css_file() instead.
  app.add_stylesheet('style.css')
...                                                                                                                                                                                                            
/home/davidh/repos/git/vispy/vispy/visuals/transforms/linear.py:docstring of vispy.visuals.transforms.MatrixTransform:1: WARNING: duplicate object description of vispy.visuals.transforms.MatrixTransform, other instance in visuals, use :noindex: for one of them                                                                                                                                                                                                                                            
/home/davidh/repos/git/vispy/vispy/visuals/transforms/linear.py:docstring of vispy.visuals.transforms.MatrixTransform.imap:1: WARNING: duplicate object description of vispy.visuals.transforms.MatrixTransform.imap, other instance in visuals, use :noindex: for one of them                                                                                                                                                                                                                                  
/home/davidh/repos/git/vispy/vispy/visuals/transforms/linear.py:docstring of vispy.visuals.transforms.MatrixTransform.map:1: WARNING: duplicate object description of vispy.visuals.transforms.MatrixTransform.map, other instance in visuals, use :noindex: for one of them                                                                                                                                                                                                                                    
/home/davidh/repos/git/vispy/vispy/visuals/transforms/linear.py:docstring of vispy.visuals.transforms.MatrixTransform.rotate:1: WARNING: duplicate object description of vispy.visuals.transforms.MatrixTransform.rotate, other instance in visuals, use :noindex: for one of them                                                                                                                                                                                                                              
/home/davidh/repos/git/vispy/vispy/visuals/transforms/linear.py:docstring of vispy.visuals.transforms.MatrixTransform.scale:1: WARNING: duplicate object description of vispy.visuals.transforms.MatrixTransform.scale, other instance in visuals, use :noindex: for one of them                                                                                                                                                                                                                                
/home/davidh/repos/git/vispy/vispy/visuals/transforms/linear.py:docstring of vispy.visuals.transforms.MatrixTransform.set_frustum:1: WARNING: duplicate object description of vispy.visuals.transforms.MatrixTransform.set_frustum, other instance in visuals, use :noindex: for one of them                                                                                                                                                                                                                    
/home/davidh/repos/git/vispy/vispy/visuals/transforms/linear.py:docstring of vispy.visuals.transforms.MatrixTransform.set_mapping:1: WARNING: duplicate object description of vispy.visuals.transforms.MatrixTransform.set_mapping, other instance in visuals, use :noindex: for one of them                                                                                                                                                                                                                    
/home/davidh/repos/git/vispy/vispy/visuals/transforms/linear.py:docstring of vispy.visuals.transforms.MatrixTransform.set_ortho:1: WARNING: duplicate object description of vispy.visuals.transforms.MatrixTransform.set_ortho, other instance in visuals, use :noindex: for one of them                                                                                                                                                                                                                        
/home/davidh/repos/git/vispy/vispy/visuals/transforms/linear.py:docstring of vispy.visuals.transforms.MatrixTransform.set_perspective:1: WARNING: duplicate object description of vispy.visuals.transforms.MatrixTransform.set_perspective, other instance in visuals, use :noindex: for one of them                                                                                                                                                                                                            
/home/davidh/repos/git/vispy/vispy/visuals/transforms/linear.py:docstring of vispy.visuals.transforms.MatrixTransform.shader_imap:1: WARNING: duplicate object description of vispy.visuals.transforms.MatrixTransform.shader_imap, other instance in visuals, use :noindex: for one of them                                                                                                                                                                                                                    
/home/davidh/repos/git/vispy/vispy/visuals/transforms/linear.py:docstring of vispy.visuals.transforms.MatrixTransform.shader_map:1: WARNING: duplicate object description of vispy.visuals.transforms.MatrixTransform.shader_map, other instance in visuals, use :noindex: for one of them                                                                                                                                                                                                                      
/home/davidh/repos/git/vispy/vispy/visuals/transforms/linear.py:docstring of vispy.visuals.transforms.MatrixTransform.translate:1: WARNING: duplicate object description of vispy.visuals.transforms.MatrixTransform.translate, other instance in visuals, use :noindex: for one of them                                                                                                                                                                                                                        
...
checking consistency... /home/davidh/repos/git/vispy/_website/README.rst: WARNING: document isn't included in any toctree
```

### CODE REVIEW

**Comment by djhoese** [comment]
Dang...we have a lot of travis environments.

**Comment by larsoner** [comment]
See also https://github.com/mne-tools/mne-python/issues/8184#issue-690155098 for an alternative if you want to go with python-scientific-ecosystem uniformity

**Comment by larsoner** [comment]
(we also upload and build our own docs to github pages using CircleCI if you want to go that route I can help set it up)

**Comment by djhoese** [comment]
@larsoner Great! I do like that theme and I really don't want to be in charge of updating the vispy/glumpy theme that we use now as browsers change (see #1906). I'll have to do some more research. Is the CircleCI stuff much different than travis? Just including some key for upload, right?

**Comment by djhoese** [comment]
Thanks again @larsoner . I spent 30 minutes reading through all the docs between this pydata theme, the sphinx multiversion, travis github pages deploy, and doctr. I didn't really understand the need for doctr because setting up a token doesn't seem complicated to me, but the doctr multiversion stuff seemed important. This sphinx multiversion tool and their docs for deploying with travis make this seem dead simple. Granted I still need to do it but yeah. I think this is the route I'll go.

**Comment by djhoese** [comment]
So we had an issue with pytest-sugar 0.9.2/.3 a while back. I just got conda-forge to merge the PR for 0.9.4 and was able to remove these restrictions. I think I'm going to merge this and we'll see what happens to the website :crossed_fingers:

**Comment by jni** [comment]
@djhoese site looks good no? 😃

**Pull request merged**
