### PR TITLE
Unpin numpy for Py>=3.7.

### PR DESCRIPTION
**Pull request by anntzer**
See discussion at #1795.

### CODE REVIEW

**Comment by djhoese** [comment]
Just to double check, this fixes the library issues on your system?

**Comment by anntzer** [comment]
yes

**Comment by djhoese** [comment]
Thanks for the quick fix for this!

**Comment by anntzer** [comment]
thanks for the quick review :)

**Comment by hmaarrfk** [comment]
Do you compile C code with numpy?
If so, you should not leave the numpy pinning loose.

If you don't, you should likely loosen the pinning on all the other versions of numpy as well.

The correct fix is to follow something like scipy's pinning
https://github.com/scipy/scipy/blob/master/pyproject.toml

IMO, pyproject.toml is just asking for trouble. I always use the `--no-build-isolation` flag anyway.

**Comment by anntzer** [comment]
I guess that would work too?
I personally don't like the pyproject.toml approach either but I've given up on fighting that, I just want things to compile fine locally :)

**Comment by hmaarrfk** [comment]
> I guess that would work too?

it isn't so much that it would work, it is that without the pinning, the package might not install.

If you for example have numpy 1.15, and compile C code with numpy 1.17+, as pyproject.toml would create for you, it may not work due to how the C-API changes.

https://github.com/scikit-image/scikit-image/issues/4261#issuecomment-557415094

You probably want the line:

```
 pip config set no-build-isolation False
```
yes, False is the actual line to set.

**Comment by djhoese** [comment]
@hmaarrfk Thanks for the insight on this. Based on what you've said it sounds like a loose numpy dependency will always be a problem since `pip` will always build/install C dependencies against the newest numpy but may not update the version of numpy in your final environment *or* of the C libraries built from other dependencies.

As far as pyproject.toml goes, as far as I understand it is the recommended way of doing build dependencies for the pip community. If there are better suggestions, let me know, but this was the easiest solution at the time.

**Comment by hmaarrfk** [comment]
It may be recommended way, but I personally don't like it.

I've experienced the value in having separate build control and source control, and pyproject encourages the combination, which isn't always advantageous.

**Comment by djhoese** [comment]
> having separate build control and source control

What are your preferences for a python package with C extensions?

**Comment by hmaarrfk** [comment]
So pyproject.toml avoids users having the command:

```
pip install -e . -vv
```

fail when because numpy installed and `setup.py` requires it before being parsed. But it doesn't ensure consistency with the isolated environment and the users' currently virtual envinronment.

I would rather users error on that command, with a non-descript message, and be forced to read the development documentation.

I don't think pyproject.toml doesn't actually help any users install from source on pypi. That often requires other system dependencies, compilers, correctly configured path, as well as obviously working with unsupported versions of the python interpretter and endianess. 

Anyway, scipy and numpy started using it, so my opinion is much less valid than theirs, but I personally have this:
```
$ cat ~/.config/pip/pip.conf 
[global]
no-build-isolation = False

# [install]
# no-dependencies = yes
```

essentially disabling `pyproject.toml` for all the projects I hack on.

**Pull request merged**
