### PR TITLE
Corrected improper use of Color.is_blank  (fixes scene/viewbox example)

### PR DESCRIPTION
**Pull request by campagnola**
Ready for review/merge.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
Do you think it would be better to make this a property instead of method? I doubt you're the only person who will make such a mistake...

**Comment by campagnola** [comment]
I was thinking the same thing.. not here, though.

**Comment by campagnola** [comment]
I take it back--I'll do it now.

**Comment by Eric89GXL** [comment]
Did the old `git grep` only reveal a few instances? :)

I'll merge once the green light pops up.

**Comment by Eric89GXL** [comment]
Looks like at least for the first commit one of the examples was broken on Travis.

**Comment by campagnola** [comment]
All is well.

**Comment by Eric89GXL** [comment]
Great, thanks for the fix.

**Pull request merged**
