### PR TITLE
Fix examples with recent numpy version

### PR DESCRIPTION
**Pull request by neok-m4700**
This PR fixes running examples with recent versions of numpy (`>= 1.18`)
(mostly related to https://github.com/numpy/numpy/pull/14620)

### CODE REVIEW

**Comment by djhoese** [comment]
Thanks for this. Do you have a copy of the warning messages that you could post here so when people google them they find this PR?

**Comment by djhoese** [comment]
One of the travis tests was failing and it seemed to be caused by an HTTP download error. I restarted it so hopefully it passes. I'm not sure on the appveyor failure.

**Comment by neok-m4700** [comment]
Error 1
-------
```python
Traceback (most recent call last):
  File "./demo/scene/oscilloscope.py", line 238, in <module>
    mic = MicrophoneRecorder()
  File "./demo/scene/oscilloscope.py", line 67, in __init__
    t = np.linspace(0, 10, rate*10)
  File "<__array_function__ internals>", line 5, in linspace
  File "$PREFIXl/lib/python3.8/site-packages/numpy/core/function_base.py", line 119, in linspace
    raise TypeError(
TypeError: object of type <class 'float'> cannot be safely interpreted as an integer.
```

Warning 1
---------
```python
./demo/gloo/unstructured_2d.py:102: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  data = np.column_stack(
```

Warning 2
---------
```python
./demo/gloo/primitive_mesh_viewer_qt.py:185: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  hbox.addStretch(1.0)
```

**Comment by djhoese** [comment]
Thanks. For appveyor, it seems they are failing because of a change in the wheel package. Would you mind removing these lines in `appveyor.yml`:

https://github.com/vispy/vispy/blob/ecb54a1632ce40f54812fcc2ed391e0a11915f76/appveyor.yml#L50-L52

I'm not actually sure what this is supposed to be showing us, but I've never used it. @larsoner chime in if you care.

**Comment by djhoese** [comment]
FYI here is the new function definition in the wheel package: https://github.com/pypa/wheel/blob/master/src/wheel/pep425tags.py#L189

**Comment by djhoese** [comment]
Master branch has now started failing with new numpy versions. Thanks for this!

**Pull request merged**
