### PR TITLE
ENH: Simple marker test

### PR DESCRIPTION
**Pull request by Eric89GXL**
This will help us know whether or not point sprites are working for people.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
Travis and AppVeyor are happy, ready for review/merge from my end.

**Comment by almarklein** [comment]
LGTM, but how does this *test* sprites? People can run this demo and see whether they see the markers or not?

**Comment by Eric89GXL** [comment]
If the sprite doesn't draw, the test fails. This was confirmed in the other thread where I suspected the user's sprites weren't drawing.

**Comment by Eric89GXL** [comment]
Maybe I don't understand your question, but I hope how the code works pretty straightforward as a standard drawing test:

1. Draw sprite visual

2. Capture screenshot

3. Check to make sure the screenshot contains something drawn (this could be made more comprehensive later by actually checking against a standard testing image, but I figured that was overkill for now)

People can run the code the standard way as part of the test suite, or they can execute it. If point sprites work, there will be no error. If point sprites fail to draw -- at least in one incarnation of the issue -- the assert will fail.

**Pull request merged**
