### PR TITLE
FIX: Minor fixes

### PR DESCRIPTION
**Pull request by Eric89GXL**
Fixes a couple problems with the CIs getting more strict. We'll see if they're happy.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
This should "fix" the CIs -- I had to add a test skip because for some unknown reason an `ArrowVisual` test was failing for old numpy. I tried for a while to fix it but couldn't, so I'll have to take a look later. But it's important for our CIs to work, so probably worth merging with the skip. Ready for review/merge from my end.

**Comment by Eric89GXL** [comment]
@rossant do you have a minute to take a quick look at this? It would be good to get it in so the currently open PRs could be tested properly.

**Comment by rossant** [comment]
LGTM, although I'm not that familiar with that part of the code.

**Comment by Eric89GXL** [comment]
Okay, I'll go ahead and merge. If others want to chime in I'm happy to make a follow-up PR.

**Pull request merged**
