### PR TITLE
FIX: add proper offset to spatial-filter fragment shader

### PR DESCRIPTION
**Pull request by kmuehlbauer**
This PR fixes an offset issue within the spatial-filters fragment shader. See discussion in #1017.

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
In #1017 @rougier suggested an example showing all interpolations in one application. It could go with this PR or separate. Suggestions?

**Comment by rougier** [comment]
LGTM

**Comment by Eric89GXL** [comment]
It seems simple enough to add to this PR if you have the time to do it

**Comment by rougier** [comment]
This PR can be merged now. The other one may need more comments.

**Comment by Eric89GXL** [comment]
Works for me. Thanks for the fix @kmuehlbauer

**Pull request merged**
