### PR TITLE
DOC: Drop installation instructions from readme

### PR DESCRIPTION
**Pull request by hoechenberger**
Refer to documentation on the website instead.

### CODE REVIEW

**Comment by djhoese** [comment]
Thanks! Any chance you could take a screenshot of the difference? Switching between github markdown and restructuredtext and slack I never remember what looks best.

**Comment by hoechenberger** [comment]
Before:
Screen Shot 2020-01-09 at 21 33 17

After:
Screen Shot 2020-01-09 at 21 33 51

**Comment by djhoese** [comment]
Interesting, it doesn't look that way on the generated docs: http://vispy.org/installation.html

**Comment by hoechenberger** [comment]
@djhoese These docs appear to have been generated from https://github.com/vispy/vispy-website/blob/09586e86066f51547a29bd080771d7084e566c9e/installation.rst, and not from the readme file this PR is concerned with :)

**Comment by hoechenberger** [comment]
Which makes me wonder why there's such a discrepancy _in content_ anyway …

**Comment by djhoese** [comment]
:man_facepalming: 

Ok, so we're mixing markdown and rst in the README.

As for the "in content" comment, do you mean you think we should just point to the official docs in the README?

**Comment by hoechenberger** [comment]
> As for the "in content" comment, do you mean you think we should just point to the official docs in the README?

That would probably make things easier to maintain, yes…

**Comment by djhoese** [comment]
Agreed. @larsoner @kmuehlbauer any objections to having the README point to the main docs site for installation instructions?

**Comment by kmuehlbauer** [comment]
@djhoese Yeah, sure, DRY is a good idea.

**Comment by hoechenberger** [comment]
@djhoese WDYT?

**Comment by djhoese** [comment]
Don't worry about the test failures. Those are being worked on in #1805.

**Comment by djhoese** [comment]
Thanks again!

**Pull request merged**
