### PR TITLE
PR: "Cube" geometry vertex colours are inconsistently defined.

### PR DESCRIPTION
**Pull request by KelSolaar**
References #898.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
LGTM, thanks for the PR! @campagnola I assume you're okay with this?

**Comment by Eric89GXL** [comment]
@KelSolaar does this solve your problem from Gitter with orientations?

**Comment by campagnola** [comment]
I suppose.. I guess I'm confused why any colors are generated in the first place, but *shrug*.

**Comment by Eric89GXL** [comment]
I think it was a matter of expediency since our examples use the colors in
a bunch of places.

**Comment by Eric89GXL** [comment]
Thanks @KelSolaar!

**Comment by KelSolaar** [comment]
@Eric89GXL Yes it does solve my issue! I will try to take a look a other places in the code whenever I have some time.

**Pull request merged**
