### PR TITLE
Add user guide

### LINKED ISSUE #803: Better documentation
* User guide
  * Introduction to VisPy
  * Interactive scientific plots
    * Line plot
    * Scatter plot
    * Image
    * Surface plot
    * Convert a matplotlib figure to VisPy (experimental)
  * The scene graph (TODO @campagnola @almarklein)
  * Custom OpenGL visualizations
    * Introduction to modern OpenGL and gloo
    * How to make a new visual
* API reference (cc @almarklein)

I can do most of it. I'll need some help with Sphinx and the build process for the website doc (@rougier and @almarklein).

### PR DESCRIPTION
**Pull request by rossant**
* This is not a full user guide but already a starting point
* This is Markdown because I hate ReST, but if needed it can be converted with `pandoc -f markdown -t rst user_guide.md -o user_guide.rst`
* There are many TODOs that could be tackled later.
* Closes #803

### CODE REVIEW

**Comment by rossant** [comment]
Ready for review.

**Comment by rossant** [comment]
appveyor failed because of `Build execution time has reached the maximum allowed time for your plan (40 minutes).`

**Comment by Eric89GXL** [comment]
Yeah, we're going to have to ignore the CIs until GitHub settles down

**Comment by Eric89GXL** [comment]
There are still TODO's left -- should I review after those are fixed?

**Comment by rossant** [comment]
I won't fix the TODOs now, and some of them are actually targetting others. Should I remove them or replace them with something less ugly?

**Comment by Eric89GXL** [comment]
I suppose this doesn't actually end up in our docs anywhere, so it's okay for now I guess.

**Pull request merged**
