### PR TITLE
Allow depth in Texture2D.

### PR DESCRIPTION
**Pull request by keunhong**
This is needed to render depth to a framebuffer texture.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
LGTM but needs some test

**Comment by djhoese** [comment]
@keunhong It's been a couple years, but any chance you would be able to add some tests for this and merge with master so we can get this merged?

**Comment by djhoese** [comment]
@keunhong Any chance you are still in a place where you could add tests for this?

**Comment by djhoese** [comment]
Ok I think I've added a couple tests for the depth stuff. I think this is good enough for a merge now. If/when the tests all pass then we can assume nothing is getting broken, merge it, and include it in the next release.

**Pull request merged**
