### PR TITLE
Fix website deploy commit message references

### PR DESCRIPTION
**Pull request by djhoese**
I noticed while working on another project and copying from VisPy that the commit messages weren't actually rendering the environment variables I was trying to use. I think this PR should fix these (currently testing with the geoxarray project).

### CODE REVIEW

**Comment by djhoese** [comment]
It works: https://github.com/geoxarray/geoxarray.github.io/

**Comment by kmuehlbauer** [comment]
Great! Thanks for fixing.

**Comment by djhoese** [comment]
> Great! Thanks for fixing.

Will it ever actually benefit us to have this information in the commit message...probably not. But it's there.

**Comment by kmuehlbauer** [comment]
@djhoese Now that we have it there we won't ever need it :grinning:

**Pull request merged**
