### PR TITLE
Cpu buffer

### PR DESCRIPTION
**Pull request by thomasdeneux**
Following issue [#1505](https://github.com/vispy/vispy/issues/1505), i implemented an optional local CPU buffer in the Buffer class. By default it is not used, but it is used by Collections so that one can set individual fields of the VertexBuffer.

### CODE REVIEW

**Comment by thomasdeneux** [comment]
Hello, this pull request was not accepted, was it? Note that after implementing this "local CPU buffer" feature, i encountered more problems with collections, so i did not continue in that direction and now i am only writing my own shaders. So even myself i am not using this feature. Should we drop it or make the effort to go until acceptance of the PR because this might be useful in the future?

**Comment by djhoese** [comment]
What kind of issues did you run in to with collections? If this gets us closer to more glumpy-like collections that are more flexible then I'm all for getting it merged.

Maybe you could merge this with current master and we'll see if the tests pass now? I have other changes (like `CPUData` -> `cpu_data`) that I'd like, but getting tests added and getting them passing is more important.

**Comment by thomasdeneux** [comment]
If i try to do a new pull request i get a button "view pull request" that sends me back here, and no button to create a new pull request. So i assume that i must first close this current PR. I try it.

**Comment by djhoese** [comment]
You can merge master in to your branch and push it to this same existing branch and the PR will update.

**Comment by thomasdeneux** [comment]
oh too late, i have already issued the new pull request...

**Comment by thomasdeneux** [comment]
did not pass the tests again... and i have difficulty reading the test reports to determine where is the problem

**Pull request closed without merging**
