### PR TITLE
Prevent translucent window with QOpenGLWidget

### LINKED ISSUE #1889: Transparency issue resurfaced for PyQt5 on OSX
A colleague noticed that our PyQt5 application that uses VisPy is showing a transparency issue that we used to see with the old version of vispy's pyqt5 backend but only on OSX (and maybe Windows). The issue is whenever you have something semi-transparent in the canvas on OSX it shows *through* the window allowing you to see the windows behind. Here is a minimal example:

```
from vispy.app import use_app
from vispy.scene import SceneCanvas
from vispy.scene.visuals import Polygon
canvas = SceneCanvas()
v = canvas.central_widget.add_view()
v.bgcolor = 'gray'
v.camera = 'panzoom'
cx, cy = (0.5, 0.5)
halfx, halfy = (0.1, 0.1)
poly_coords = [(cx - halfx, cy - halfy),
               (cx + halfx, cy - halfy),
               (cx + halfx, cy + halfy),
               (cx - halfx, cy + halfy)]
poly = Polygon(poly_coords, color=(1.0, 0.0, 0.0, 0.5), border_color=(1.0, 1.0, 1.0, 0.2),
               border_width=3,  parent=v.scene)
app = use_app('pyqt5')
canvas.show()
app.run()
```

Which produces something like:

image (1)

Googling around shows that this should be related to the alpha buffer configured here:

https://github.com/vispy/vispy/blob/77f016a0c6121e1b0c024bdf4e03d5bf84aa9879/vispy/app/backends/_qt.py#L233

However, setting this to -1 (default `alpha_size` is 8) or commenting out this line still produce the same results on OSX. I've had a coworker (CC @rayg-ssec) test this to confirm. On my Ubuntu laptop I don't see this issue at all. I'm wondering if any of the napari folks and other contributors have seen something like this (CC @tlambert03 @kmuehlbauer @larsoner @sofroniewn @kne42)?

### PR DESCRIPTION
**Pull request by asnt**
Fix #1889

Fixes it for me on Linux with wayland.

### CODE REVIEW

**Comment by asnt** [comment]
The test failure is here: https://github.com/vispy/vispy/runs/2693602731?check_suite_focus=true#step:11:86
Not sure why. It succeeds on my system.

**Comment by djhoese** [comment]
For the record here are the error messages:

```
vispy/app/tests/test_simultaneous.py:124: in test_multiple_canvases
    _update_process_check(canvas, 127)
vispy/app/tests/test_simultaneous.py:40: in _update_process_check
    assert_allclose(ss[:, :, :3], goal[:, :, :3], atol=1)
E   AssertionError: 
E   Not equal to tolerance rtol=1e-07, atol=1
E   
E   Mismatched elements: 30000 / 30000 (100%)
E   Max absolute difference: 127.
E   Max relative difference: 1.
E    x: array([[[0, 0, 0],
E           [0, 0, 0],
E           [0, 0, 0],...
E    y: array([[[127., 127., 127.],
E           [127., 127., 127.],
E           [127., 127., 127.],...
----------------------------- Captured stdout call -----------------------------
([4, 4], 3)
draw 0
  0      : [0.5, 0.5, 0.5, 1.0]
           check 127
!!!!!!!!!! FAIL  [  0 255]
__________________________ test_functionality_desktop __________________________
vispy/gloo/gl/tests/test_functionality.py:44: in test_functionality_desktop
    _test_functionality('gl2')
vispy/gloo/gl/tests/test_functionality.py:97: in _test_functionality
    _draw1()
vispy/gloo/gl/tests/test_functionality.py:521: in _draw1
    _check_result()
vispy/gloo/gl/tests/test_functionality.py:561: in _check_result
    assert_equal(pix2, (255, 0, 0))
vispy/testing/_testing.py:99: in assert_equal
    raise AssertionError(_format_msg(msg, std_msg))
E   AssertionError: (0, 0, 0) not equal to (255, 0, 0)
___________________________ test_functionality_proxy ___________________________
vispy/gloo/gl/tests/test_functionality.py:53: in test_functionality_proxy
    _test_functionality('gl2 debug')
vispy/gloo/gl/tests/test_functionality.py:97: in _test_functionality
    _draw1()
vispy/gloo/gl/tests/test_functionality.py:521: in _draw1
    _check_result()
vispy/gloo/gl/tests/test_functionality.py:561: in _check_result
    assert_equal(pix2, (255, 0, 0))
vispy/testing/_testing.py:99: in assert_equal
    raise AssertionError(_format_msg(msg, std_msg))
E   AssertionError: (0, 0, 0) not equal to (255, 0, 0)
_________________________ test_functionality_pyopengl __________________________
vispy/gloo/gl/tests/test_functionality.py:62: in test_functionality_pyopengl
    _test_functionality('pyopengl2')
vispy/gloo/gl/tests/test_functionality.py:97: in _test_functionality
    _draw1()
vispy/gloo/gl/tests/test_functionality.py:521: in _draw1
    _check_result()
vispy/gloo/gl/tests/test_functionality.py:561: in _check_result
    assert_equal(pix2, (255, 0, 0))
vispy/testing/_testing.py:99: in assert_equal
    raise AssertionError(_format_msg(msg, std_msg))
E   AssertionError: (0, 0, 0) not equal to (255, 0, 0)
_______________________________ test_log_parser ________________________________
vispy/gloo/tests/test_glir.py:102: in test_log_parser
    assert lines[i] == json.dumps(['FUNC', 'clearColor', 1.0, 1.0, 1.0, 1.0])
E   assert '["FUNC", "co... false, true]' == '["FUNC", "cl....0, 1.0, 1.0]'
E     - ["FUNC", "clearColor", 1.0, 1.0, 1.0, 1.0]
E     + ["FUNC", "colorMask", false, false, false, true]
```

It looks like your changes are causing an all black result. Not great, but I think I've had issues with these tests in the pass on OSX (but these failures are on linux). We'll need to figure this. The last failure should be pretty simple to fix (change what line it should expect the `clearColor` command), but the other ones are more concerning. Let's see what the others in #1889 say about this working for them.

**Comment by djhoese** [comment]
@asnt Any luck figuring this out?

**Comment by asnt** [comment]
> @asnt Any luck figuring this out?

I haven't had a chance to look at fixing the tests yet.

On the Qt side, there is this [bug](https://bugreports.qt.io/browse/QTBUG-74285) and a [fix](https://codereview.qt-project.org/c/qt/qtbase/+/255297) since version 5.12. That could be related but there are more issues listed with the QOpenGLWidget that I didn't look into yet.

@djhoese I'll have to delay the work on this. Feel free to modify the branch if you have anything.

**Comment by almarklein** [comment]
With these changes, the same test as the one on CI fails for me. Good news is that I can now try to find out what causes it.

**Comment by almarklein** [comment]
@asnt Could you try moving the flush one line down (just after resetting the color mask)? With that change, the test passes for me.

**Comment by asnt** [comment]
> @asnt Could you try moving the flush one line down (just after resetting the color mask)? With that change, the test passes for me.

@almarklein The test still fails on my side (Note: It was failing on my side before as well, contrarily to what I wrote above.) I pushed the change anyway, for the record.

**Comment by asnt** [comment]
Dumping the glir commands from the test,
```diff
iff --git a/vispy/gloo/tests/test_glir.py b/vispy/gloo/tests/test_glir.py
index d303614a..4ade0a1f 100644
--- a/vispy/gloo/tests/test_glir.py
+++ b/vispy/gloo/tests/test_glir.py
@@ -79,6 +79,9 @@ def test_log_parser():
     glir_file.seek(0)
     lines = glir_file.read().split(',\n')

+    for line in lines:
+        print(line)
+
     assert lines[0][0] == '['
     lines[0] = lines[0][1:]
```
gives
```
[["CURRENT", 0, 1]
["FUNC", "colorMask", false, false, false, true]
["FUNC", "clear", 16384]
["FUNC", "colorMask", true, true, true, true]
["FUNC", "flush"]
["CURRENT", 0, 1]
["FUNC", "colorMask", false, false, false, true]
["FUNC", "clear", 16384]
["FUNC", "colorMask", true, true, true, true]
["FUNC", "flush"]
["CURRENT", 0, 1]
["FUNC", "colorMask", false, false, false, true]
["FUNC", "clear", 16384]
["FUNC", "colorMask", true, true, true, true]
["FUNC", "flush"]
["CURRENT", 0, 1]
["FUNC", "clearColor", 1.0, 1.0, 1.0, 1.0]
["FUNC", "clear", 17664]
["FUNC", "finish"]]
```
I guess, this sequence is different from the one expected in the test because of the newly introduced
The series of
```
["FUNC", "colorMask", false, false, false, true]
["FUNC", "clear", 16384]
["FUNC", "colorMask", true, true, true, true]
["FUNC", "flush"]
```
was introduced by this PR and is not expected in the original test.

**Comment by asnt** [comment]
Should we have specific test for pyqt5?

**Comment by almarklein** [comment]
Ah wait, I meant the `test_simultaneous`, and actually the `test_functionality` failed for me as well, but with this latest change they pass. Just like in CI. So if with this latest change this pr still prevents translucent windows for you, we're nearly there! :)

The test that you referenced should simply be adapted. But note that we can also not rely on these new GLIR commands to be presents (depends on the backend used).

**Comment by asnt** [comment]
> Ah wait, I meant the `test_simultaneous`, and actually the `test_functionality` failed for me as well, but with this latest change they pass. Just like in CI.

Ah, I see, great! My bad, I was focused on the last one.

> So if with this latest change this pr still prevents translucent windows for you, we're nearly there! :)

Yes, it does.

> The test that you referenced should simply be adapted. But note that we can also not rely on these new GLIR commands to be presents (depends on the backend used).

Not sure yet what is the proper way to check which backend is being used. I'll try to have a look over the coming days but if you have inspiration, feel free to push a change.

**Comment by djhoese** [comment]
On mobile so can't find the exact code, but I know there are some tests that skip themselves if the backend is a certain one.

**Comment by almarklein** [comment]
I fixed the test. This should be ready.

**Comment by asnt** [comment]
@almarklein Thanks!

**Comment by djhoese** [comment]
If you're both happy with this, feel free to merge @almarklein.

**Pull request merged**
