### PR TITLE
Add touch event on OS X

### PR DESCRIPTION
**Pull request by rossant**
This adds preliminary multitouch support on OS X (Qt backend). It works fine on my end so it should be ready to go.

cc @Eric89GXL @nippoo

### CODE REVIEW

**Comment by campagnola** [comment]
Generates a lot of `WARNING: Got touch without getting TouchBegin for id 171` messages for me..

**Comment by rossant** [comment]
What version of OS X? What example have you run?

**Comment by campagnola** [comment]
Kubuntu 14.04 (let's say it's roughly equivalent to OSX 12.5 ;)
I get this error running any of the examples (multiple errors printed while touching the screen).

**Comment by rossant** [comment]
Ah, I didn't even realized this could be used on touchscreen... (I did this PR for the OS X trackpad)
It looks like a bug in Ubuntu or Qt. Could you try the fix in the first link below? Otherwise, should we just restrict this on OS X for now? We can add support for touchscreen later.

https://gabrbedd.wordpress.com/2012/07/10/getting-multitouch-qt-on-ubuntu-12-04/
https://bugs.launchpad.net/ubuntu/+source/qt4-x11/+bug/1007847

**Comment by campagnola** [comment]
No luck from those. It appears to be a bug with the combination of QGLWidget and XInput, so it should be enough to disable it for Linux (only lines 293/294 need to be disabled).

**Comment by rossant** [comment]
ok @campagnola, done. This is ready to merge if travis is happy.

**Comment by rossant** [comment]
done

**Comment by campagnola** [comment]
Thanks @rossant! Anyone else want a peek before merge?

**Comment by Eric89GXL** [comment]
Cool! Looks like it's actually a pretty simple bit of code. LGTM +1 for merge

**Comment by Eric89GXL** [comment]
Thanks @rossant

**Pull request merged**
