### PR TITLE
[MRG] Add TextureCube object and port skybox example from glumpy

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
**What does this implement/fix?**
Port skybox example from Glumpy #818 

**Additional information**
1) I fixed the `offset` tuple in the `set_data()` method of the `GlirTextureCube` class in `vispy/gloo/glir.py` because I wasn't sure about what it exactly does.

2) I did not find any alternatives for `trackball` so I used another way to interact from:
`examples/demo/gloo/terrain.py`. Most likely there is a more practical way.

3) I stored the images on my machine and tested locally but I guess they can be uploaded in `vispy/demo-data`.

4) I am not sure about the location of `skybox.py`, I put it in `examples/demo/gloo` by default.

It is still a work in progress but here is a rendering:
skybox

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
Travis cannot test the example yet because the images can't be loaded.

**Comment by GuillaumeFavelier** [comment]
Honestly, I don't know why Travis is not happy this time. 
Except from that, I still wonder how to handle the `offset` parameter of the `set_data()` method in the `GlirTextureCube` class.
Feel free to tell me what you think.

**Comment by GuillaumeFavelier** [comment]
I just realise this is a duplicate of #1303.

**Comment by djhoese** [comment]
@GuillaumeFavelier Am I correct that this now has all of the functionality of #1303 included? What were the differences between your PR and that one?

**Comment by GuillaumeFavelier** [comment]
Both PRs added the *cube mapping* feature needed for #818.

@keunhong created `TextureCubeMap` and `GlirTextureCubeMap` classes, I called them `TextureCube` and `GlirTextureCube` respectively in this version. I wasn't sure of my implementation and since #1303 had already been reviewed, I decided to use his (merged in this [commit](https://github.com/vispy/vispy/pull/1589/commits/ee17f5c968a97737c2c5879d2f62d6997c9adc03)).

I think most of the differences are in the example script itself. @keunhong decided to demonstrate the cube mapping with generated textures and automatic camera interaction if I understood correctly whereas I tried to reproduce the *trackball* camera interaction, loaded the sky images and kept the example script fairly similar to the [source](https://github.com/glumpy/glumpy/blob/master/examples/skybox.py) as I considered it as a port.

**Pull request merged**
