### PR TITLE
Fix various issues with shading in the MeshVisual

### PR DESCRIPTION
**Pull request by asnt**
Some fixes to the recent shading filter for correct/consistent behaviour.

### CODE REVIEW

**Comment by djhoese** [comment]
@asnt Should this PR be merged or should I wait for #2029 to be finished (currently a WIP)?

**Comment by asnt** [comment]
> @asnt Should this PR be merged or should I wait for #2029 to be finished (currently a WIP)?

@djhoese This one is ready. (I'll try to finish #2029 soon.)

**Comment by djhoese** [comment]
Just to be sure, this is for "correct/consistent" results, but these changes change the overall way the shading used to work, right?

Any idea if this PR would fix #1998?

**Comment by asnt** [comment]
> Just to be sure, this is for "correct/consistent" results, but these changes change the overall way the shading used to work, right?

0c3b75e and 9036567 fix this implementation.
549a705 fixes an issue that probably existed before this filter.

The main difference with the shading before this filter is the shininess parameter. In the specular reflection, the shininness `alpha` is now the exponent `(...)^alpha` to follow the standard equations in [[1]]. Before this filter, the exponentiation was `(...)^(1/alpha)`, which is not standard, as far as I can tell. To me, this creates less confusion.

[1]: https://en.wikipedia.org/wiki/Phong_reflection_model

> 
> Any idea if this PR would fix #1998?

Indeed, partly. 9036567 fixes the specular highlight appearing on the non-illuminated side. Otherwise, I am suspecting an issue with the normals in the icosahedron-based sphere. (The recent MeshNormals visuals can help identify that.) I'll have a closer look at it when possible.

**Comment by djhoese** [comment]
Thanks @asnt as always.

**Pull request merged**
