### PR TITLE
clipping planes performance: do not create a new function willy nilly

### PR DESCRIPTION
**Pull request by brisvag**
Over at napari we noticed that with some specific GPUs (Intel Iris so far), we gat very bad performance when recompiling programs, due to these lines:

https://github.com/vispy/vispy/blob/16d8c5bd8694df9c18086e6fad31ffbaa08abaf4/vispy/visuals/filters/clipping_planes.py#L103-L114

In `0.10`, the `Function` was cached, which turned out to be problematic when working with multiple instances of the filter (due to [this issue](https://rednafi.github.io/reflections/dont-wrap-instance-methods-with-functoolslru_cache-decorator-in-python.html).

However, now a new `Function` gets create every time, even when unnecessary. Granted, in napari we are mistakenly calling this setter *way* too often, which we are fixing, but this should probably be checked in vispy as well.

### CODE REVIEW

**Review by djhoese — APPROVED** [review]
Compared to the caching that was done before, this seems fine.

**Comment by djhoese** [comment]
No I don't. We could try forcing the version of PyQt6 installed. Version 6.4.0 just came out on PyPI 10 hours ago: https://pypi.org/project/PyQt6/

**Comment by djhoese** [comment]
These release notes aren't very helpful: https://riverbankcomputing.com/news/PyQt_v6.4.0_Released

**Comment by brisvag** [comment]
Approved and passing, merging!

**Pull request merged**
