### PR TITLE
Filter away annoying qnotifier warning.

### PR DESCRIPTION
**Pull request by hmaarrfk**
Workaround for https://github.com/vispy/vispy/issues/1787

### CODE REVIEW

**Comment by djhoese** [comment]
Thoughts on a blacklist like spyder:

https://github.com/spyder-ide/spyder/blob/25a788288e33d7e210e3cf1647c57db10bf863f6/spyder/app/mainwindow.py#L278-L282

**Comment by hmaarrfk** [comment]
seems a little over the top, but whatever gets this in faster ;)

**Comment by hmaarrfk** [comment]
The logic for it is so complicated due to the backward compatibility with PyQt4, ;)

**Comment by hmaarrfk** [comment]
Well blacklist logic added.

**Comment by djhoese** [comment]
Thank you.

**Comment by djhoese** [comment]
If this turns out to be something in QtConsole that gets fixed in the future (https://github.com/jupyter/qtconsole/issues/332) then we can remove this ignore since I assume it is trying to tell us something useful in the usual case.

**Comment by hmaarrfk** [comment]
wow that was fast. Is it too much to ask for 0.6.4?

**Comment by djhoese** [comment]
No I was actually wanting to do it for the `version.py` stuff I changed recently. Probably today or this weekend depending on how some of the rest of my work goes.

**Comment by hmaarrfk** [comment]
All good, the workaround I provided in the post kinda works, although there is a slight chance of race condition, but pretty minor in the grand scheme of things!

**Pull request merged**
