### PR TITLE
WIP: Geometry shaders

### PR DESCRIPTION
**Pull request by campagnola**
Adds support for geometry shaders to `gloo`.

### CODE REVIEW

**Comment by campagnola** [comment]
Note: changes to `gl/glplus.py` address an issue that is also fixed by #1306. It looks like their changes are a better solution, so we can revert glplus.py here if #1306 is merged.

**Comment by campagnola** [comment]
Update: this PR is basically finished, but it causes some unit test failures that I have not had time to look into. If anyone else wants to pick this up, that'd be great.

**Comment by davidh-ssec** [comment]
@campagnola I'll take a swing at resolving the conflicts and seeing what I can do. I'm going to make a PR to merge with this PR so I can test my merge without losing the easy-to-read history of this PR.

**Comment by davidh-ssec** [comment]
Yeah @campagnola the tests fail...because they weren't updated to match your changes :)

**Pull request closed without merging**
