### PR TITLE
Use stacklevel in DeprecationWarnings.

### PR DESCRIPTION
**Pull request by Carreau**
That give the correct location most of the time for where the fix/update
should be instead of pointing into vispy codebase.

That make updates by consumer easier (and thus more likely),
And in turn should make you more confident about removing deprecated
things.

### CODE REVIEW

**Comment by djhoese** [comment]
Wow, awesome. Thank you for this. I always forget about `stacklevel` when dealing with this kind of stuff. @kmuehlbauer or @almarklein any issue with these? Their placement seems to make sense to me.

**Comment by Carreau** [comment]
> Wow, awesome. Thank you for this. I always forget about `stacklevel` when dealing with this kind of stuff.

No worries, this is one of my pet peeves, with another that I didn't fixed here which is "since which version" things are deprecated. For example vispy/gloo/texture.py's seem to have been deprecated for 7 years since 0.4.  And honestly I don't get why default value for stacklevel is not 2 , it's almost always the right value (or a mandatory parameter).

**Comment by kmuehlbauer** [comment]
@Carreau Thanks, this is really worth it and it is also requested in other packages I contribute.

We could think about adding deprecation tests which will fail, if not removed in a specific version. But that would mean to have at least a RC release to get these tests into effect.

**Review by almarklein — APPROVED** [review]
Awesome!

**Comment by djhoese** [comment]
> with another that I didn't fixed here which is "since which version" things are deprecated. 

Pull requests welcome :smile:

**Pull request merged**
