### PR TITLE
Improve `plot.scatter()`

### PR DESCRIPTION
**Pull request by brickgao**
Hi,

This PR is referring to `vispy.plot.scatter()`.

It finish three points in #742: 

* Use a white background as a default
* Allow passing an array of scalars for colors, with a colormap
* Choose black `face_color` other than white

### CODE REVIEW

**Comment by almarklein** [comment]
I think the default background color (and also other style stuff) should be the same for all vp.plot functions, so should probably be implemented globally. Also note that @Eric89GXL is working on a new `vispy.plot` api to replace the current one.

**Comment by Eric89GXL** [comment]
yes @brickgao can you hold off on modifying `vispy.plot` for now? I'm working on it in #804 currently.

**Comment by brickgao** [comment]
@Eric89GXL I got it ;)

**Comment by Eric89GXL** [comment]
Okay @brickgao my PR has been merged. Can you try making your changes to `LinePlotVisual`, and then making sure they're also reflected in `vispy.plot.plotwidget.PlotWidget`, which uses `LinePlot`? Feel free to close this PR and open a new one if that's easier, which I suspect it will be.

**Comment by brickgao** [comment]
@Eric89GXL ok ;)

**Pull request closed without merging**
