### PR TITLE
Clip step size based on maximum detail on an 8K monitor

### PR DESCRIPTION
**Pull request by jni**
This limit is based on intuition rather than a rigorous analysis, but the limit is much looser than what was there before, and we now warn and clip rather than raising, which I think is more user-friendly.

See also #2587

### CODE REVIEW

**Review by brisvag — APPROVED** [review]
Looks great to me :) maybe @djhoese has some opinion though? From the other PR, rationale here is:

> if you are drawing a single-pixel cube, you probably don't need more resolution in z than you have in xy. So, how about setting a minimum step size of 1/8192, so that people with 8K monitors can "losslessly" draw single pixel cubes in 8K glory, and the rest of us can draw pixel volumes in the full range of accuracy in between 1 and 1/8K?

**Comment by brisvag** [comment]
Did some testing as well, all great! I woudl say let's get this in :)

**Comment by aganders3** [comment]
I am doing some testing locally and this test now fails because it no longer raises `ValueError`. Any idea why it passed in the checks for this PR?

https://github.com/vispy/vispy/blob/4f061ba23ddac3131eb0d1d955573dd71c9a3d2f/vispy/visuals/tests/test_volume.py#L46-L48

**Comment by aganders3** [comment]
Actually I think it should be changed back to still raise the `ValueError` for step size <= 0, and the warning for step size between (0, min_step_size).

**Comment by jni** [comment]
> I am doing some testing locally and this test now fails because it no longer raises ValueError. Any idea why it passed in the checks for this PR?

wow, that's weird.

> Actually I think it should be changed back to still raise the ValueError for step size <= 0, and the warning for step size between (0, min_step_size).

Great plan! 🧠 Are you making a PR or should I?

**Comment by aganders3** [comment]
> Great plan! 🧠 Are you making a PR or should I?

You are fast, haha. I can do it!

**Pull request merged**
