### PR TITLE
Bump VisPy version

### LINKED ISSUE #688: Bump VisPy version?
Should we bump the version to 0.4.0-dev or something? Currently it is 0.3.0, which doesn't seem right.

### PR DESCRIPTION
**Pull request by rossant**
To 0.4.0-dev. The current indicated version (0.3.0) is wrong...

Closes #688.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
Thanks, I've been meaning to do that...

**Comment by almarklein** [comment]
@rossant I think you're pushing branches to upstream instead of origin. Not a big deal, but I think our policy was to use our own clones for PR's?

**Comment by Eric89GXL** [comment]
Yeah, it's better to push to our own repos so that the main one doesn't get polluted with people's working branches.

**Comment by rossant** [comment]
??? I'm confused, I thought I was pushing to my fork! Sorry about that.
I generally do `git push origin` (and origin is definitely my fork), but sometimes I just do `git push`. I thought this was always a shortcut for `origin`...

**Comment by rossant** [comment]
Here is what I did:

```
cyrille@gigabyte:/data/git/vispy$ git remote -v
kaptan	https://github.com/mfkaptan/vispy.git (fetch)
kaptan	https://github.com/mfkaptan/vispy.git (push)
luke	https://github.com/lcampagn/vispy.git (fetch)
luke	https://github.com/lcampagn/vispy.git (push)
origin	https://github.com/rossant/vispy.git (fetch)
origin	https://github.com/rossant/vispy.git (push)
upstream	https://github.com/vispy/vispy.git (fetch)
upstream	https://github.com/vispy/vispy.git (push)
cyrille@gigabyte:/data/git/vispy$ git push origin
```

**Pull request merged**
