### PR TITLE
Add connect to line plot

### PR DESCRIPTION
**Pull request by JoeXinfa**
Add kwarg `connect` to lines at plot level.

### CODE REVIEW

**Comment by djhoese** [comment]
Doesn't this perform the same purpose as `line_kind` in the existing interface? I think I would prefer if these two options could be combined, if possible. Also the docstring for that class will need to be updated.

What is your use case for needing the `connect` keyword argument?

**Comment by JoeXinfa** [comment]
Thanks for the quick response. I've been busy at work and just get time reply you. No it's not the same; `connect` defines which vertices are connected by lines while `line_kind` is for the style of lines e.g. solid, dashed or dotted. I updated the docstring accordingly. An example is below.
```
import numpy as np
import vispy.plot as vp

x = np.array([0,1,2,3,4,5])
y = np.array([0,1,2,3,4,5])
data = (x, y)
connect = np.array([[0,1], [2,3], [4,5]])

fig = vp.Fig(show=False)
ax = fig[0, 0]
line = ax.plot(data, symbol='o', connect=connect)

if __name__ == '__main__':
    fig.show(run=True)
```
My use case is plotting the block lines in oil & gas exploration (Gulf of Mexico, for example). The data are vertices (XY coordinates) and segments (which vertices are connected).

**Comment by djhoese** [comment]
Just curious, how would you plot this with matplotlib? Is there an interface that vispy should be adding for plotting lines like yours? Is a plot actually what you want or do you just need the lines on the screen (plotting versus SceneCanvas/Canvas with Visuals)?

**Comment by JoeXinfa** [comment]
I don't know if matplotlib can plot this or not (connect is the key). With the change in this PR, vispy is enough for my need. We usually don't just plot the block lines, but overlay them with lots of other things such as coastlines, wells, seismic surveys, leases, etc. Therefore, I need the scene/canvas that I can add/remove items and pan/zoon interactively. Thanks.

**Comment by djhoese** [comment]
Ok but you want the plot axes, ticks, axes labels, etc? I'm not completely against merging this PR I just want to make sure things are being used as intended and if not figure out what use cases aren't being handled by existing functionality.

**Comment by JoeXinfa** [comment]
Yes I do. This PR is quite simple, just remove the hard-coded `connect` in `scene.LinePlot` and expose to `def plot()` so user can set at that level. To my knowledge, it is only better than before. Is there any reason that people would be against it?

**Comment by djhoese** [comment]
@JoeXinfa You are right, this only adds more functionality for the user. My hesitation is only because this reveals a low-level interface in a high-level interface. So far users haven't needed this and if this functionality isn't available in matplotlib then I'm wondering if it requires other changes. Now that I think about it more I suppose this is possible in matplotlib as separate line segments which in vispy would require separate LineVisuals and would have terrible performance.

**Comment by JoeXinfa** [comment]
That's true. Before I found this `connect`, I tried plot the thousands of segments as separate LineVisuals, which choked on memory. Thank you.

**Pull request merged**
