### PR TITLE
FIX: Unbundle freetype

### LINKED ISSUE #1276: Error on Windows with loading freetype?
I'm having issues running e.g. the `axes_plot.py` example:

```
PS C:\Users\Administrator\vispy\examples\basics\scene> python .\axes_plot.py > windows.log
WARNING: Traceback (most recent call last):
  File ".\axes_plot.py", line 58, in <module>
    app.run()
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\app\_default_app.py", line 62, in run
    return default_app.run()
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\app\application.py", line 137, in run
    return self._backend._vispy_run()
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\app\backends\_qt.py", line 229, in _vispy_run
    return app.exec_()
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\app\backends\_qt.py", line 431, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\app\backends\_qt.py", line 431, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\app\backends\_qt.py", line 703, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\util\event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\util\event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\util\event.py", line 471, in _invoke_callback
    cb(event)
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\scene\canvas.py", line 207, in on_draw
    self._draw_scene()
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\scene\canvas.py", line 253, in _draw_scene
    self.draw_visual(self.scene)
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\scene\canvas.py", line 291, in draw_visual
    node.draw()
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\scene\visuals.py", line 98, in draw
    self._visual_superclass.draw(self)
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\visuals\visual.py", line 588, in draw
    v.draw()
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\visuals\visual.py", line 432, in draw
    if self._prepare_draw(view=self) is False:
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\visuals\text\text.py", line 443, in _prepare_dra
w
    self._font._lowres_size) for t in text])
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\visuals\text\text.py", line 443, in <listcomp>
    self._font._lowres_size) for t in text])
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\visuals\text\text.py", line 157, in _text_to_vbo

    glyph = font[char]
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\visuals\text\text.py", line 69, in __getitem__
    self._load_char(char)
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\visuals\text\text.py", line 83, in _load_char
    _load_glyph(self._font, char, self._glyphs)
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\util\fonts\_freetype.py", line 47, in _load_glyp
h
    from ...ext.freetype import (FT_LOAD_RENDER, FT_LOAD_NO_HINTING,
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\ext\freetype.py", line 10, in <module>
    from ._bundled.freetype import *  # noqa
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\ext\_bundled\freetype.py", line 184, in <module>

    __dll__ = CDLL(FT_Library_filename)
  File "C:\Anaconda3\lib\ctypes\__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt4) at 0x6bd12d85f8>> for DrawEvent
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt4) at 0x6bd12d85f8>> repeat 2
PS C:\Users\Administrator\vispy\examples\basics\scene> cat .\windows.log
PS C:\Users\Administrator\vispy\examples\basics\scene> Start-BitsTransfer-
PS C:\Users\Administrator\vispy\examples\basics\scene> Start-Transcript
Transcript started, output file is C:\Users\Administrator\Documents\PowerShell_transcript.WIN-S4OOT383BGP.NNT6Qtwu.2016
0926134428.txt
PS C:\Users\Administrator\vispy\examples\basics\scene> python .\axes_plot.py
WARNING: Traceback (most recent call last):
  File ".\axes_plot.py", line 58, in <module>
    app.run()
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\app\_default_app.py", line 62, in run
    return default_app.run()
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\app\application.py", line 137, in run
    return self._backend._vispy_run()
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\app\backends\_qt.py", line 229, in _vispy_run
    return app.exec_()
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\app\backends\_qt.py", line 431, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\app\backends\_qt.py", line 431, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\app\backends\_qt.py", line 703, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\util\event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\util\event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\util\event.py", line 471, in _invoke_callback
    cb(event)
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\scene\canvas.py", line 207, in on_draw
    self._draw_scene()
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\scene\canvas.py", line 253, in _draw_scene
    self.draw_visual(self.scene)
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\scene\canvas.py", line 291, in draw_visual
    node.draw()
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\scene\visuals.py", line 98, in draw
    self._visual_superclass.draw(self)
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\visuals\visual.py", line 588, in draw
    v.draw()
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\visuals\visual.py", line 432, in draw
    if self._prepare_draw(view=self) is False:
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\visuals\text\text.py", line 443, in _prepare_dra
w
    self._font._lowres_size) for t in text])
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\visuals\text\text.py", line 443, in <listcomp>
    self._font._lowres_size) for t in text])
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\visuals\text\text.py", line 157, in _text_to_vbo

    glyph = font[char]
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\visuals\text\text.py", line 69, in __getitem__
    self._load_char(char)
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\visuals\text\text.py", line 83, in _load_char
    _load_glyph(self._font, char, self._glyphs)
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\util\fonts\_freetype.py", line 47, in _load_glyp
h
    from ...ext.freetype import (FT_LOAD_RENDER, FT_LOAD_NO_HINTING,
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\ext\freetype.py", line 10, in <module>
    from ._bundled.freetype import *  # noqa
  File "C:\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.5.egg\vispy\ext\_bundled\freetype.py", line 184, in <module>

    __dll__ = CDLL(FT_Library_filename)
  File "C:\Anaconda3\lib\ctypes\__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt4) at 0xf5fb1e95f8>> for DrawEvent
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt4) at 0xf5fb1e95f8>> repeat 2
PS C:\Users\Administrator\vispy\examples\basics\scene> Stop-Transcript
Transcript stopped, output file is C:\Users\Administrator\Documents\PowerShell_transcript.WIN-S4OOT383BGP.NNT6Qtwu.2016
```

This appears to maybe be linked to Freetype?

### LINKED ISSUE #1327: VisPy automatically downloads and uses freetype253.dll. This is not OK.
I was shocked and dismayed to discover that running `examples\basics\visuals\line.py` would automatically download a `dll` file (`freetype253.dll`) without even asking me first. 

*This is not in any way OK.*

Worse, this happens *on import* of `vispy.util.fonts`. Nothing much should happen on import of any module, because there are other reasons for importing a module besides wanting to call any of the functions in it. For example, Sphinx imports modules when it makes documentation from docstrings, and so modules should not do anything on import that you don't want to happen when building docs. This includes downloading files from the internet.

(If a module contains a lot of functions that each require the same setup to be performed before the first time they're called, a good solution is to make a decorator that does the setup if it hasn't been done already, and then calls the decorated function. For the end user this will work just the same, with the exception that importing the module has no side-effects.)

Worse still, the file was downloaded using plain-text http only, and no verification was performed to ensure that github.com really was github.com or that the downloaded file was the intended file. It was just loaded and used, no questions asked.

I *insist* on being in control when it comes to what files are downloaded and executed from the internet, and I think it is very reasonable demand that VisPy, being a reputable python module, does not do such things.

I urge you in the strongest possible way to make VisPy at least *ask* before downloading and running executable files, no matter their origin (I even want to be asked about pure data downloads -- who knows, maybe I'm on mobile data and don't want to download a big file right now -- but in this issue I want to focus on the executable files).

In my opinion this warrants an immediate bugfix release once fixed.

### PR DESCRIPTION
**Pull request by larsoner**
Let's just use `freetype-py`.

Closes #1276.
Closes #1327.

### CODE REVIEW

**Comment by larsoner** [comment]
OpenSans is only ~1 MB. I'm tempted just to add it to the repo instead of having it as part of the repo. By doing that and having this PR, then we don't have anything that people need to download, and we don't have to do anything magical for our wheels.

Okay with you @djhoese?

**Comment by larsoner** [comment]
@rougier I expected `pip install freetype-py` to "just work" but the Windows AppVeyor builds [fail with](https://ci.appveyor.com/project/vispy/vispy/builds/25893998/job/i3r39cnh8en7jbp3):
```
...
    try:
        _lib = ctypes.CDLL(filename)
    except (OSError, TypeError):
        _lib = None
>       raise RuntimeError('Freetype library not found')
E       RuntimeError: Freetype library not found
```
Any ideas?

**Comment by kmuehlbauer** [comment]
@larsoner 
The wheel used (freetype_py-2.1.0.post1-py2.py3-none-any.whl) does not include the `dll`. Not sure why `pip` decides to use this wheel and not the `freetype_py-2.1.0.post1-py2.py3-none-win*` flavour (where the `dll` is included). ping @rougier

**Comment by kmuehlbauer** [comment]
@larsoner 

Added printout check for PEP425 wheel tags.

**Comment by kmuehlbauer** [comment]
OK, AFAIU and assuming from the printout of the tag check, `py2-none-win32` is higher ranking than `py2-none-any` and `py3-none-win_amd64`is higher ranking than `py3-none-any`. But for some reason the `-none-any` wheel gets installed. 

There are some RuntimeWarnings connected with this, not sure if there is an issue with that.

```
C:\conda\envs\test\lib\site-packages\wheel\pep425tags.py:80: RuntimeWarning: Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
  warn=(impl == 'cp')):
C:\conda\envs\test\lib\site-packages\wheel\pep425tags.py:84: RuntimeWarning: Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
  warn=(impl == 'cp')):
C:\conda\envs\test\lib\site-packages\wheel\pep425tags.py:90: RuntimeWarning: Config variable 'Py_UNICODE_SIZE' is unset, Python ABI tag may be incorrect
  sys.version_info < (3, 3))) \
python setup.py develop

```

**Comment by djhoese** [comment]
Is there a reason we can't install `freetype-py` from conda-forge?

**Comment by larsoner** [comment]
For users using conda, probably, but things should work with pip, too

**Comment by djhoese** [comment]
Ah yes, of course. I was just thinking about the tests. You are right though.

**Comment by larsoner** [comment]
For now I'll just force it to install the proper version and assume that `freetype-py` is just not getting along with AppVeyor for some reason.

CIs are green other than what appears to be a spurious Travis error, feel free to merge if you're happy @djhoese

**Comment by djhoese** [comment]
Restarting the travis examples failure which usually makes it pass. Some day I really need to look in to this since it seems like some kind of caching issue or race condition (fails the first time often, passes the second time every time). Then I'll merge.

**Pull request merged**
