### PR TITLE
Updated pinnings for python 3.8

### PR DESCRIPTION
**Pull request by hmaarrfk**

### CODE REVIEW

**Comment by hmaarrfk** [comment]
It seems that this is important for
https://github.com/vispy/vispy/blob/master/vispy/visuals/text/_sdf_cpu.pyx

**Comment by djhoese** [comment]
So what I'm understanding from the original PR and issue (#1799 and #1796) is that the main issue regarding numpy versions is if you have a loose definition you can have some packages built with one version and other packages built with another, but that won't determine what version is actually installed in the environment.

This looks good to me. I'll merge this next time I'm online and give others time to comment if they'd like.

**Comment by hmaarrfk** [comment]
You want to ensure that all packages were built with older versions of numpy than the one that is ultimately installed in the users enviroent.

**Comment by djhoese** [comment]
Thanks for this. Sorry I lost track of it.

**Comment by hmaarrfk** [comment]
It was meant to be easy to pull in when you found time.

Thanks for finding it!

No issue on the delay

**Pull request merged**
