### PR TITLE
enforce same type for norm and renorm so that ufunc true_divide doesn't error

### PR DESCRIPTION
**Pull request by alisterburt**
Hi! First, thanks for vispy 🥰 
I came across a bug when trying to use expose the different shading modes with meshes in napari, traceback below

```python
WARNING: Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/napari/lib/python3.9/site-packages/vispy/app/backends/_qt.py", line 825, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/napari/lib/python3.9/site-packages/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/napari/lib/python3.9/site-packages/vispy/util/event.py", line 473, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  File "/opt/homebrew/Caskroom/miniforge/base/envs/napari/lib/python3.9/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/napari/lib/python3.9/site-packages/vispy/scene/canvas.py", line 217, in on_draw
    self._draw_scene()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/napari/lib/python3.9/site-packages/vispy/scene/canvas.py", line 266, in _draw_scene
    self.draw_visual(self.scene)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/napari/lib/python3.9/site-packages/vispy/scene/canvas.py", line 304, in draw_visual
    node.draw()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/napari/lib/python3.9/site-packages/vispy/scene/visuals.py", line 99, in draw
    self._visual_superclass.draw(self)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/napari/lib/python3.9/site-packages/vispy/visuals/mesh.py", line 519, in draw
    Visual.draw(self, *args, **kwds)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/napari/lib/python3.9/site-packages/vispy/visuals/visual.py", line 435, in draw
    if self._prepare_draw(view=self) is False:
  File "/opt/homebrew/Caskroom/miniforge/base/envs/napari/lib/python3.9/site-packages/vispy/visuals/mesh.py", line 514, in _prepare_draw
    if self._update_data() is False:
  File "/opt/homebrew/Caskroom/miniforge/base/envs/napari/lib/python3.9/site-packages/vispy/visuals/mesh.py", line 360, in _update_data
    self._normals.set_data(md.get_vertex_normals(), convert=True)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/napari/lib/python3.9/site-packages/vispy/geometry/meshdata.py", line 346, in get_vertex_normals
    norm /= renorm
TypeError: ufunc 'true_divide' output (typecode 'd') could not be coerced to provided output parameter (typecode 'l') according to the casting rule ''same_kind''
Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

I guess this is happening because my inputs have dtype int64 (for a very simple test mesh)
```python
vertices = np.array([[0, 0, 0], [0, 20, 10], [10, 0, -10], [10, 10, -10]])
faces = np.array([[0, 1, 2], [1, 2, 3]])
```

I enforced the same type for `norm` and `renorm` in `MeshData.get_vertex_normals()` and the problem went away so here's a PR - can change if there's a different way you'd like to solve this issue though!

### CODE REVIEW

**Comment by djhoese** [comment]
Interesting. I'll take a closer look at this sometime this weekend (hopefully). I'm not against the method you chose, but I'm wondering if in the low-level gloo code if VisPy converts vertices to floats anyway, so maybe the Mesh visuals should force them to floats right away (if I'm understanding the dtypes involved here).

**Comment by alisterburt** [comment]
that all makes sense, thanks for the quick feedback!

**Comment by djhoese** [comment]
So this all starts with `get_face_normals` which has this chunk of code:

https://github.com/vispy/vispy/blob/76b5e47c2bf81dfbaa8e834a931e118aaaecb98e/vispy/geometry/meshdata.py#L296-L306

So depending on the indexing mode, the normals are going to have the same dtype of `v` (the vertices) or they will be `np.float32`. But then the vertices for the unindexed mode look like they should also be float32:

https://github.com/vispy/vispy/blob/76b5e47c2bf81dfbaa8e834a931e118aaaecb98e/vispy/geometry/meshdata.py#L568

Except for maybe this case:

https://github.com/vispy/vispy/blob/76b5e47c2bf81dfbaa8e834a931e118aaaecb98e/vispy/geometry/meshdata.py#L231

So maybe the `astype` should go there?

@larsoner @kmuehlbauer Any idea if there is a benefit to allowing vertices as integers over floats?

**Comment by djhoese** [comment]
@alisterburt Would you mind trying to add an `astype` on this line:

https://github.com/vispy/vispy/blob/76b5e47c2bf81dfbaa8e834a931e118aaaecb98e/vispy/geometry/meshdata.py#L231

to fix this? If you also remove your current `astype`, does this fix the issue you were seeing?

**Comment by alisterburt** [comment]
@djhoese unfortunately I couldn't reproduce the issue locally, sorry about that. I'm not sure exactly what has changed since I had the issue but it's possible that napari is now enforcing types in places it wasn't before.

In any case - I cast to float32 where you suggested and that didn't break anything either... given that I can't reproduce the error I'm also happy if you prefer to just close this PR and move on

**Comment by djhoese** [comment]
I keep going back and forth on this. Part of says that this a simple fix just to force the type to what it needs to be, but another part says that I don't want to accidentally break someones usage for something that rarely comes up. Additionally, the fix from the user point of view is relatively simple (convert your verts to floats).

If someone in the future is reading this and is sick of running into this error, please comment and we'll reopen this and consider implementing the `astype` somewhere closer to the vertex creation.

**Pull request closed without merging**
