### PR TITLE
Avoid explicit loop in computing normals in MeshData

### PR DESCRIPTION
**Pull request by soraxas**
Test timing: (assuming you have two folder named as `MeshData__original` and `MeshData__PR`, which corresponds to the **main** branch and this **PR** branch:
```py
from vispy_main_branch.geometry import MeshData as MeshData__original
from vispy_PR_branch.geometry import MeshData as MeshData__PR
import numpy as np
import time

def run(N_vertex, N_faces):
    ###############################################
    # prepare data
    np.random.seed(0)

    vertices = np.random.rand(N_vertex, 3).astype(np.float32)
    faces = np.random.choice(N_vertex, size=(N_faces, 3))

    # remove rows that are repeated
    faces.sort(axis=1)
    faces = np.unique(faces, axis=0)

    # remove rows with repeated vertices indices
    faces = faces[(faces[:, 0] != faces[:, 1]) & (faces[:, 0] != faces[:, 2]) & (faces[:, 1] != faces[:, 2])]
    ###############################################

    mesh_ori = MeshData__original(vertices=vertices, faces=faces)
    mesh_pr = MeshData__PR(vertices=vertices, faces=faces)

    t = time.time()
    vn_ori = mesh_ori.get_vertex_normals()
    elapsed_ori = time.time() - t
    t = time.time()
    vn_pr = mesh_pr.get_vertex_normals()
    elapsed_pr = time.time() - t

    assert np.isclose(vn_ori, vn_pr).all()

    print(f"{N_vertex},{N_faces},{elapsed_ori},{elapsed_pr}")


N_vertex = 10_000
N_faces = 10_000

print("N_vertex,N_faces,original,PR")
while N_vertex < 5_000_000:
    run(N_vertex, N_faces)
    N_vertex = int(N_vertex * 1.1)

# N_vertex = 10_000
# N_faces = 10_000

# while N_faces < 5_000_000:
#     run(N_vertex, N_faces)
#     N_faces = int(N_faces * 1.1)
```

timings_N_vertex
timings_N_faces

(plotted with the following)
```py
import matplotlib.pyplot as plt
import numpy as np
import csv

with open('out.csv', 'r') as f:
    reader = csv.reader(f)
    label = next(reader)
    data = np.array(list(list(map(float, line)) for line in reader))


plt.plot(data[:, 0], data[:, 2], label=label[2])
plt.plot(data[:, 0], data[:, 3], label=label[3])
plt.xlabel(label[0])
plt.ylabel("time (sec)")

plt.legend()
plt.savefig("timings_N_vertex.png")
# plt.show()
```

### CODE REVIEW

**Comment by djhoese** [comment]
Awesome! I'll try to find time in the next couple days to review this.

@asnt Assuming you have any time available, your feedback on this would be appreciated.

**Comment by asnt** [comment]
This looks good to me. Thank you for the patch @soraxas and for the benchmarks.

Additionally, I would suggest to extend this PR with specific tests for vertex normals. See https://github.com/vispy/vispy/pull/2434 as an example.

@djhoese

**Comment by asnt** [comment]
Same issue: https://github.com/vispy/vispy/pull/2069

**Comment by djhoese** [comment]
Merged along with #2434. Thanks!

**Pull request closed without merging**
