### PR TITLE
Gtk3 backend

### PR DESCRIPTION
**Pull request by stsdc**
Hello everyone!
I'm trying to add Gtk3 backend and struggling with this error:
```bash
 File "/home/stanislaw/Projekty/vispy/examples/basics/gloo/start.py", line 10, in <module>
    app.use_app("gtk3")
  File "/home/stanislaw/Projekty/vispy/vispy/app/_default_app.py", line 47, in use_app
    default_app = Application(backend_name)
  File "/home/stanislaw/Projekty/vispy/vispy/app/application.py", line 49, in __init__
    self._use(backend_name)
  File "/home/stanislaw/Projekty/vispy/vispy/app/application.py", line 230, in _use
    if not mod.available:
AttributeError: module 'vispy.app.backends._gtk3' has no attribute 'available'
```
Looks like something with imports, but I can't figure out what is going on :confused:

### CODE REVIEW

**Comment by djhoese** [comment]
Thanks for putting this together. For the available exception, you'll need to have something like this:

https://github.com/vispy/vispy/blob/7f3f6f60c8462bb8a3a8fa03344a2e6990b86eb2/vispy/app/backends/_pyqt5.py#L31

You can see earlier in the above module where it has a caught exception and uses that exception message as the "why_not" value. This lets the backend importing parts of vispy know what's up with the backend even when it can't be imported/used.

**Comment by rougier** [comment]
Is there something missing in the backend ?

**Comment by stsdc** [comment]
Well, basically everything :grimacing: 

Unfortunately I don't have enough time and knowledge to push this forward :disappointed:

**Comment by rougier** [comment]
Ok, I'll close the PR. Feel free to re-open.

**Pull request closed without merging**
